<?php 
	$url_new = $this->url(array('module'=>'rsvacl','controller'=>'acl','action'=>'add',	));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("VEIW_USER_CONTROLLER");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("VEIW_USER_CONTROLLER");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate('ADD_NEW');?>
				</a>
			</div>
			<div class="portlet-body form">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php echo $this->form;?>
					</div>
		   </div>
		</div>
	</div>
</div>
	