<?php 
	$url_new = $this->url(array('module'=>'category','controller'=>'index','action'=>'add',));
	$url_edit = $this->url(array('module'=>'category','controller'=>'index','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'category','controller'=>'index','action'=>'delete',));
	$url_cancel = $this->url(array('module'=>'category','controller'=>'index','action'=>'index',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("LOCATION_LIST");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ADD_LOCATION");?>
			</div>
			<div class="tools pull-right">
				<a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="<?php echo $url_edit;?>" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("PARENT");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('parent');?>
								</div>
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("CATEGORY_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('cat_name');?>
								</div>
												
							</div>
							<div class="form-group">
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('status');?>
								</div>
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('remark');?>
								</div>
							</div>
						<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
									<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									<a href="<?php echo $this->baseUrl();?>/category/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								</label>
							</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>