<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("MAKE_INVOCIE");?></title>
<div class="row">
<marquee style="margin-top:-20px;" behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5">យើងត្រូវការ ការយល់ព្រមពី ផ្នែកគណនេយ្យ /ហិរញ្ញវត្ថុ ឫអ្នកដែលមានសិទ្ធ ដើម្បី <span style="color:red;">បង្កើតជាវិក័យបត្រ និង របាយការណ៏ប្រគល់ទំនិញ</span> / We need approval from  or person who have permission to <span style="color:red;">issue invoice and Delivery Report</span> ! </marquee>
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("INVOICE_APPROVED");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'approved'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $this->product[0]['branch_code'];?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("INVOICE_APPROVED");?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
		                				
		                				<td width="35%" style="text-align: left;font-size: 13px;" valign="top">
		                					<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff;">&nbsp;&nbsp;Trasfer Note</div>
		                					<ul class='pur_info'>
			                					<li style="text-align: left;"><strong>Branch Name : </strong><?php echo $this->rs['re_from'];?></li>
			                					<li style="text-align: left;"><strong>Request To.: </strong><?php echo $this->rs['re_to'];?></li>
			                					<li style="text-align: left;"><strong>Request No.: </strong><?php echo $this->rs['re_no'];?></li>
			                					<li style="text-align: left;"><strong>Date : </strong><?php echo date("d/m/Y",strtotime($this->rs['re_date']));?></li>
		                					</ul>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; font-size:13px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th>&nbsp;<?php echo $tr->translate("NUM");?></th>
							<th><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></th>
							<th width="10%">&nbsp;<?php echo $tr->translate("SERIAL_NUM");?></th>
							<th>&nbsp;<?php echo $tr->translate("QTY");?></th>
		                <?php $num=1; 
		               
		                if(!empty($this->rs_detail))foreach ($this->rs_detail AS $index => $rs){
							$raw_qty = $rs["qty"];
							$array = explode(".",$rs["qty"]);
							$qty = $array[0];
							$qty_unit = ($raw_qty*$rs["qty_measure"]) - ($rs["qty_measure"]*$array[0]);
							$l_qty = 0;
							if(abs($raw_qty)>0){
								if(abs($qty)>0 and $qty_unit>0){
									$l_qty = $qty." ".$rs["measure"]." & ".round($qty_unit)." ".$rs["unit_label"];
								}elseif(abs($qty)==0 and $qty_unit>0){
									$l_qty = round($qty_unit)." ".$rs["unit_label"];
								}elseif(abs($qty)>0 and $qty_unit==0){
									$l_qty =  $qty." ".$rs["measure"];
								}
							}else{
								$l_qty = 0;
							}
						?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $l_qty;?></td>
						</tr>
						   <?php 
                    }?>
                   
					
		            </tbody>
		           </table>
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		 <table align="center" width="100%" >
							   <tbody>
							   <tr style="font-size: 11px;">
							        <td valign="bottom" style="text-align:center; font-family:'Khmer MEF2';white-space: nowrap;"><textarea name="app_remark" id="app_remark" class="form-control" rows="3" cols="80" placeHolder="Approval Comment Here"></textarea></td>
							        <td style="width:10%;"></td>
									<td style="width:40%;font-family:'Khmer MEF2';white-space: nowrap;">
							        <select name="approved_name" id="approved_name" class="form-control select2me">
							        	<option value="1">Approved</option>
							        	<option value="2">Not Approved</option>
							        </select><input type="hidden" name="id" id="id" value="<?php echo $this->product[0]['id'];?>" />
									<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->product[0]['branch_id'];?>" />
									
							        </td>
							   </tr>
							</tbody>
						</table>
		
		<div class="form-group">
			<label  class="col-md-12 col-md-offset-3 col-md-8">
				<label class="col-md-3 control-label"><a href="<?php echo $this->baseUrl();?>/sales/invoiceapprove/" ><button style="width:90%;" type="button" class="btn red btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a></label>
				<div class="col-md-3 control-label"><button type="submit" name="print" value="print" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></div>
		        <div class="col-md-3 control-label"><button type="submit" name="saveprint" value="saveprint" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?></button></div>
			</label>
		</div>
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 

 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = parseFloat(net_total)-parseFloat(deposit);
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
