<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->product;
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TRANSFER_LIST");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-2">
									<?php echo $formFilter->getElement('tran_num');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('to_loc');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('tran_date');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('type');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('status');?>
								</div>
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
							
				</div>
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="sample_2" style="font-size:11px">
							<thead style="font-size:11px">
								<tr>
									<th><?php echo $tr->translate("NO");?></th>
									<th><?php echo $tr->translate("TRANSFER_NO");?></th>
									<th><?php echo $tr->translate("LOCATION");?></th>
									<th><?php echo $tr->translate("DATE_TRANSFER");?></th>
									<th><?php echo $tr->translate("GET_IN_DATE");?></th>
									<th><?php echo $tr->translate("TRANSFER_BY");?></th>
									<th><?php echo $tr->translate("STATUS");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody>
								<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
								<tr class="odd gradeX">
									<td class="center"><?php echo $key+1;?></td>
									<td><?php echo $row["tran_no"]?></td>
									<td><?php echo $row["re_tran"]?></td>
									<td><?php echo $row["date_tran"]?></td>
									<td><?php echo $row["date"]?></td>
									<td><?php echo $row["user_tran"]?> </td>
									<td class="center">
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>
									<td>
										<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
									</td>
								</tr>
								<?php }}?>
							</tbody>
							</table>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->

</div>