<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'transfer','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->product;
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TRANSFER_LIST");?>
			</div>
			<!--<div class="caption" style="float:right">
					<a href="<?php echo $url_new;?>" class="btn btn-sm red" style="line-height: 35px;">
						<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
					</a>
			</div>-->
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('avd_search');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
								<!--<div class="col-md-2">
									<?php //echo $formFilter->getElement('type');?>
								</div>
								<div class="col-md-2">
									<?php echo $formFilter->getElement('status');?>
								</div>-->
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
					</div>
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						
						<div class="portlet-body">
							<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("BRANCH");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TRANSFER_FROM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("APP_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PEDDING");?></th>
								<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($rs)){ foreach ($rs as $key => $row){
									$edit_status = '';
									if($row["ap_pedding"]==4){
										$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
									}
									
							?>
								
								<tr class="odd gradeX">
									<td class="center"><?php echo $key+1;?></td>
									<td><?php echo $row["re_tran"]?></td>
									<td><?php echo $row["tran_no"]?></td>
									<td><?php echo $row["to_tran"]?></td>
									<td><?php echo $row["date_tran"]?></td>
									<td><?php echo $row["appr_status"]?></td>
									<td><?php echo $row["appr_pedding"]?></td>
									<td class="center">
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>
									<td><?php echo $row["user"]?> </td>
									<td class="center">
										<?php if($row["receive_id"]>0){?>
											<a <?php //echo $edit_status;?> href="<?php echo $this->baseUrl();?>/product/transfer/editreceive/id/<?php echo $row["receive_id"]?>"><?php echo  $tr->translate("EDIT_RECEIVE");?></a> | 
											<a <?php //echo $edit_status;?> href="<?php echo $this->baseUrl();?>/product/transfer/viewreceive/id/<?php echo $row["id"]?>"><?php echo  $tr->translate("PRINT");?></a>
										<?php }else{?>
										<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/product/transfer/addreceive/id/<?php echo $row["is_transfer"]?>"><?php echo  $tr->translate("MAKE_RECEIVE");?></a> |  
										<?php }?>	
										
									</td>
								</tr>
								<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->

</div>