<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
//$db = new Purchase_Model_DbTable_DbPriceCompare();
//print_r($this->product);
?>
<title>Purchase Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PURCHASE_REPORT");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<!--<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>-->
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:15px">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	   .center{text-align:center;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["branch_code"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php //echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:15px; margin-top:25px; font-family:'Khmer OS Muol Light';">ប័ណ្ណស្នើផ្ទេរទិញទំនិញ</li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>ក្រុមហ៊ុន កាណាខនគ្រីត </p><p>ផ្នែកបញ្ជាទិញ និងគ្រប់គ្រងតម្លៃ</p>
									</div>-->
								</td>
						</tr>
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody>
		                			<tr>
		                				
										
										<td width="70%"></td>
		                				<td width="30%" style="text-align: left;font-size: 12px;" valign="top">
											<table width="100%" style="font-size: 12px; font-weight:600;">
												
												<tr style="line-height:20px;">
													<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_FROM");?> :</td>
													<td style="text-align: right;"><?php echo $this->product[0]['tran_location'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_NO");?> :</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['tran_no'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("TRANSFER_TO");?> :</td>
													<td style="text-align: right;"><?php echo $this->product[0]['tran_to_location'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['req_no'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: right;white-space: nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_tran']));?></td>
												</tr>
											</table>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td>
		            <table border="1" class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-size:12px !important; margin-top:10px;" width="100%" cellspacing="0">
		                 <tbody>
						 <tr style="background:#ccc;font-size:13px !important; line-height:40px;">
							<th class="tdheader" width="5%">&nbsp;<?php echo $tr->translate("NUM");?></th>
							<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
							<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
							<th class="tdheader">&nbsp;<?php echo $tr->translate("QTY_REQUEST");?></th>
							<th class="tdheader">&nbsp;<?php echo $tr->translate("QTY_TRANSFER");?></th>
							<th class="tdheader">&nbsp;<?php echo $tr->translate("NOTE");?></th>
						</tr>
						
						<?php 
							if(!empty($this->product)){ $total = 0;  foreach($this->product as $key=>$rs){$index = $key+1; 
							$count = count($this->product);
							$qty_unit = number_format($rs["qty_unit"],0);;
							$qty_per_unit = number_format($rs["qty_per_unit"],0);
							if($qty_unit>0 && $qty_per_unit>0){
								$qty_tran = $qty_unit." ".$rs["measure"]." ".$qty_per_unit." ".$rs["unit_label"];
							}else if($qty_unit<=0 && $qty_per_unit>0){
								$qty_tran = $qty_per_unit." ".$rs["unit_label"];
							}else if($qty_unit>0 && $qty_per_unit<=0){
								$qty_tran= $qty_unit." ".$rs["measure"];
							}
							
							
							$raw_qty = $rs["qty_request"];
							$array = explode(".",$rs["qty_request"]);
							$qty = $array[0];
							$qty_unit = ($raw_qty*$rs["qty_measure"]) - ($rs["qty_measure"]*$array[0]);
							$l_qty = 0;
							if(abs($raw_qty)>0){
								if(abs($qty)>0 and $qty_unit>0){
									$l_qty = $qty." ".$rs["measure"]." & ".round($qty_unit)." ".$rs["unit_label"];
								}elseif(abs($qty)==0 and $qty_unit>0){
									$l_qty = round($qty_unit)." ".$rs["unit_label"];
								}elseif(abs($qty)>0 and $qty_unit==0){
									$l_qty =  $qty." ".$rs["measure"];
								}
							}else{
								$l_qty = 0;
							}
						?>
							<tr>
								<td class="center"><?php echo $index;?></td>
								<td>&nbsp;&nbsp;<?php echo $rs["item_code"];?>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;<?php echo $rs["item_name"];?>&nbsp;&nbsp;</td>
								<td class="center"><?php echo $l_qty;?></td>
								<td class="center"><?php echo $qty_tran;?></td>
								<td>&nbsp;&nbsp;<?php echo $rs["remark"];?>&nbsp;&nbsp;</td>
							</tr>
						<?php }}?>
						<?php if($count<10){
								$count_i = 10-$count;
								for($i=1;$i<=$count_i;$i++){
									
								
						?>
							<tr>
								<td class="center"><?php echo $index+$i; ?></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						<?php }}?>
						<!--<tr>
							<td colspan="4" style="border-bottom:1px solid #fff; border-left:1px solid #fff;"></td>
							<td>Total</td>
							<td><?php echo $total;?></td>
						</tr>-->
						
		                </tbody>
		           </table>
		              <br>
		              <table align="center" width="100%" >
						   <tbody>
						   <tr style="font-size: 12px;">
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">ប្រធានឃ្លាំង</td>
						        <th></th>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អ្នកប្រគល់</td>
						        <th></th>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">ប្រធានផ្នែក</td>
								<th></th>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អ្នកទទួល</td>
						   </tr>
						    <tr style="font-size: 12px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000; "></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
								<td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
