<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PROVINCE_LIST"));
?>	
<?php //$frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'province','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <?php //echo $frm->getElement("title");?>
  <?php //echo $frm->getElement('status_search');?>
</form>
<?php echo $this->list;?>