<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'pricelevel','action'=>'add',));
	$url_sarch = $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'type-price',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("PRODUCT_PRICE");?></title>

						
						
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRICE_TYPE_LIST");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('price_type');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php echo $this->list; ?>
					</div>
		   </div>
		</div>
	</div>
</div>