<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('DAILY_PLANNING'));
$user_id = Application_Model_DbTable_DbGlobal::GlobalgetUserId();		
?>
<?php  $dailywork= $this->frm_dailywork;?>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DAILY_PLANNING");?>
			</div>
			<div class="caption pull-right">
				<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'index','action'=>'index')); ?>" class="btn btn-sm green  pull-right">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form id="frm" class="form-horizontal" method="post" action="<?php echo $this->url(array('module'=>'dailywork','controller'=>'index','action'=>'add')); ?>" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("To_DO_TASK")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("work");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("TASK_TYPE")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("projectname");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("CUSTOMER_NAME")?></label>
								<div class="col-md-7">
									<?php echo $dailywork->getElement("customer_id");?>
								</div>
								<div class="col-md-1">
                                <button type="button" onclick="popupcustomer();" class="btn green delete col-md-12 ">
									<i class="fa fa-plus" style="margin-left: -11px;"></i>
									<span>Add New </span>
								</button>
							</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("DATE")?></label>
								<div class="col-md-8">
									<div class="input-icon right"><i class="fa fa-calendar"></i>
										<?php echo $dailywork->getElement("start_date");?>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("User")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("user");?>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Status")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("status");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Description")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("description");?>
								</div>
							</div>
					<div class="form-group">
							<div class="col-md-4">
							</div>
							<div class="col-md-2">
								<div class="input-icon right col-md-12" >
									<a class="col-md-12" href="<?php echo $this->baseUrl();?>/dailywork/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
								</div>
							</div>
							<div class="col-md-4">
								<button type="submit" name="save_close" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
					</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>



<?php $form = $this->form_customer; ?>
<div id="customerpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php //echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmcustomer" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Branch Name");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cu_code'); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_phone'); ?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CON_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_contact_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CON_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i><?php echo $form->getElement('contact_phone'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_TYPE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('customer_type'); ?>
									</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Customer Level");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_level'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ADDRESS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("txt_address");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("PROVINCE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('province'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-2">
							<?php echo $tr->translate("EMAIL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_mail'); ?>
								</div>
							</div>
					</div>
					
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" onclick="addNewCustomer();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CUSTOMER")?> </button>
						</label>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>
 <script>
 $('#frm').submit(function() {
		customer_id=$("#customer_id").val();
		if(customer_id==0 || customer_id=='' || customer_id==-1){
			alert("សូមជ្រើសរើសអតិជន!");
			$('#customer_id').select2('open');
			return false;	
		}
		identity =$("#projectname").val();
		if(identity=='' || identity==-1){
			alert("សូមជ្រើសរើសប្រភេទការងារដែលបានធ្វើ");
			$('#projectname').select2('open');
			return false;
		}
		
	});
	
 function popupcustomer(){
		$('#customerpopup').modal('show');
	}
	
 jQuery(document).ready(function(){
	 //alert(<?php echo $user_id;?>);
	$('#user').attr("value",'<?php echo $user_id;?>').attr("selected",true);                       
   // $("#user").select2();
});
 function getCustomerInfo(){
	customer_id = $("#customer_id").val();
	if(customer_id==-1){
		$('#customerpopup').modal('show');
	}
}
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	txt_contact_name = $("#txt_contact_name").val();
	if(txt_contact_name==''){alert("សូមបញ្ជូលឈ្មោះអ្នកទំនាក់ទំនង !"); $("#txt_contact_name").focus();return false;} 
	contact_phone = $("#contact_phone").val();
	if(contact_phone==''){alert("សូមបញ្ជូលលេខទំនាក់ទំនង !"); $("#contact_phone").focus();return false;} 
	txt_address = $("#txt_address").val();
	if(txt_address==''){alert("សូមបញ្ជូលអាសយដ្ឋានរបស់អតិថិជន !"); $("#txt_address").focus();return false;} 
	$.ajax({
        url: "<?php echo $url_add_customer;?>",
        type: "post",
        data: $('#frmcustomer').serialize(),
        success: function(data){
            rs = $.parseJSON(data);
             $('#customer_id').append($("<option></option>").attr("value",rs['cus_id']).attr("selected",true).text(txt_contact_name));                       
             $("#customer_id").select2();
			$('#customerpopup').modal('hide');
			$('#frmcustomer').trigger("reset");
        },
        error:function(err){
            alert("faile insert");
           
        }
    });
}
function viewCustomer(){
	id = $("#customer_id").val();
	
	if(id!=-1 && id!='' && id!=0){
		window.open('<?php echo $this->url(array('module'=>'sales','controller'=>'customer','action'=>'edit')); ?>'+'/id/'+id, '_blank');
	}
}
</script>	