<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DAILYWORK')); 
?>
<?php  $dailywork= $this->frm_project;?>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DAILY_WORK_CATEGORY");?>
			</div>
			<div class="caption pull-right">
				<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'project','action'=>'index')); ?>" class="btn btn-sm green  pull-right">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form id="frm" class="form-horizontal" method="post" action="" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("TASK_CATEGORY_NAME")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("project");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("DATE")?></label>
								<div class="col-md-8">
									<div class="input-icon right"><i class="fa fa-calendar"></i>
										<input class="form-control form-control-inline date-picker" id="start_date" name="start_date" value="<?php echo date("m/d/Y")?>"  type="text" >
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Status")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("status");?>
								</div>
							</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
						    <a href="<?php echo $this->baseUrl();?>/dailywork/project"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
					</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>