<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'index'));
	$url_new = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("Customer Payment")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_METHOD");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="payment_method" id="payment_method" onchange="checkControll();" class="form-control select2me">
										<option value="1">Payment By Customer</option>
										<option value="2">Payment By Invoice</option>
									</select>
								</div>
							</div>
							<label class="control-label col-md-2"> <?php echo $tr->translate("CUSTOMER_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("customer_id");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Invoice");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_id');?>
								</div>
							</div>
							<label class="control-label col-md-2">Customer Information
							</label>
							<div class="col-md-4">
								<div class="input-icon right" style="border:1px dotted #ccc;min-height: 35px;">
									
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Receipt No.");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("receipt"); ?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa fa-calendar"></i>
								<?php echo $form->getElement("date_in");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_TYPE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("payment_name");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("CHEQUE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("cheque");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("bank_name");?>
								</div>
							</div>
							
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									
								</div>
							</div>
						</div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>
									<th><?php echo $tr->translate("វិក័យបត្រ");?></th>
									<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
									<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
									<?php echo $tr->translate("EXCHANGE_RATE");?>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("exchange_rate");?>
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("ជំពាក់សរុប​ :");?> Total<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> (Paid)
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid_dollar");?>
								</div>
							</div>	
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid_riel");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> (Paid)
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">ប្រាក់នៅសល់ (Balance)​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("balance");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-3"></div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/sales/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-2">
								<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							<div class="col-md-3"></div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
function paidtotal(type){//1=dollar,2=riel
	paid_dollar = $("#paid_dollar").val();
	paid_riel = $("#paid_riel").val();
	dollar_fromriel = parseFloat(paid_riel/$("#exchange_rate").val());
	all_paid =  parseFloat(paid_dollar) + parseFloat(dollar_fromriel);
	all_paid = (all_paid).toFixed(2);
	$("#paid").val(all_paid);
	doRemain();
}
function checkpayment(){
	payment_id = $("#payment_name").val();
	if(payment_id==2){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );}
}
function checkControll(){
	$("#table_order").html("");
	$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0);
	payment_method = $("#payment_method").val();
	if(payment_method==1){
		$( "#invoice_id" ).attr( "readOnly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
    }
}
<?php $urlgetinvoice =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'getinvoice')); ?>
function getInvoice(type){
	if(type==1){
		post_id=$("#customer_id").val();
		$( "#invoice_id" ).attr( "readonly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		post_id=$("#invoice_id").val();
		$( "#customer_id" ).attr( "readonly", true );
		$( "#invoice_id" ).attr( "readOnly", false );
	}
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id,'type_id':type},
			success: function(data){	
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("DEL");?></th>';
					template+='<th><?php echo $tr->translate("NUM");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃ/ខែ/ឆ្នាំ");?></th>';
					template+='<th><?php echo $tr->translate("វិក័យបត្រ");?></th>';
					template+='<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>';
					template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				for(i=0;i<data.length;i++){
					if(i==0){
						$("#customer_id").val(data[i].customer_id);
						$("#customer_id").select2();
					}
					index=i+1;
					template+='<tr style="height:30px;">';
			            template+='<td ><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].date_sold+'</td>';
						template+='<td >'+data[i].sale_no+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
						template+='<td >'+data[i].net_total+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td >'+data[i].discount_value+'<input type="hidden" value='+data[i].discount_value+' id="discount'+index+'" name="discount'+index+'"/></td>';
						template+='<td >'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
						template+='<td >'+data[i].balance+'<input type="hidden" value='+data[i].balance+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					
					if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}
				}
				$('#table_order').append(template);
				if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
			},
			error:function(e){
				alert("error"+e);
			}
		});	
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//subtotal += Number($('#subtotal'+rowIDArray[n]).val());
		//paid +=Number($('#paid_amount'+rowIDArray[n]).val());
		//discount +=Number($('#discount'+rowIDArray[n]).val());
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
		
	}
	//var alltotal = Number(subtotal - discount).toFixed(2);
	$('#all_total').val(subtotal);
	//$('#paid').val(paid.toFixed(2));
	$('#paid').val(0);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#balance').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}

</script>	