<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url_submit =  $this->url(array('module'=>'product','controller'=>'damagedstock','action'=>'add'));
$url_cancel =  $this->url(array('module'=>'product','controller'=>'damagedstock','action'=>'index'),null,true);
$url_getcurrentitem =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'get-current-quantity'));
$url_getProduct =  $this->url(array('module'=>'product','controller'=>'damagedstock','action'=>'get-product'),null,true);
$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("ADJUST_STOCK");?></title>
<br/>
<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ADJUST_STOCK");?>
			</div>
			<div class="tools">
				<a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">	
					<div class="form-group">
						<label class="col-md-2 control-label"><?php //echo $tr->translate("RECEIVE_FROM");?></label>
						<div class="col-md-4">
						</div>
						
						<label class="col-md-2 control-label"><?php echo $tr->translate("BRANCH");?></label>
						<div class="col-md-4">
							<?php echo $formFilter->getElement('from_loc');?>
						</div>
					</div>
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption" style="width:100%">
								<?php echo $formFilter->getElement('pro_name');?>
							</div>
						</div>
					</div>
													
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-cogs"></i><?php echo $tr->translate("PRODUCT_LIST");?>
							</div>
						</div>	
							<div class="portlet-body">
								<div class="table-responsive">
									<table class="table table-bordered">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
												<th><?php echo $tr->translate("CURRENT_QTY");?></th>
												<th><?php echo $tr->translate("DAMAGED_UNIT");?></th>
												<th><?php echo $tr->translate("DAMAGED_PER_UNIT");?></th>
												<th><?php echo $tr->translate("REMAIN_QTY");?></th>
												<th><?php echo $tr->translate("REMARK");?></th>
												<th><?php echo $tr->translate("ACTION");?></th>
											</tr>
										</thead>
										<tbody id="tr_location" style="font-size:12px;">
										</tbody>
									</table>
								</div>
								<input type="hidden" name="identity" id="identity" value="<?php //echo $identity;?>" >
							</div>
							<div class="form-group">
								<div class="form-group">
									<div class="col-md-3">
									</div>
									<div class="col-md-3">
										<a href="<?php echo $this->baseUrl();?>/product/damagedstock"><button type="button" class="btn blue btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
									</div>
									<div class="col-md-3">
										<div class="input-icon right">
											<button type="submit" name="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
										</div>
									</div>
									<div class="col-md-3">
										<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									</div>
							</div>
							</div>
					</div>
				</div>
			</form>
		</div>
</div>
<script type="text/javascript">

jQuery(document).ready(function(){
	//addRow();
});
var index=0;
url_get_qty = '<?php echo $this->url(array('module'=>'product','controller'=>'damagedstock','action'=>'get-product'))?>';
function addNew(){
	
	id = $("#pro_name").val();
	location_id = $("#from_loc").val();
	
	index++;
	$.ajax({
        url: url_get_qty,
        type: "post",
        data: {'id':id,'location_id':location_id},
        success: function(val){
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#qty_unit_"+i).val());
					newqty = newqty+1;
					$("#qty_unit_"+i).val(newqty);
					//diferQTY(i);
					return false;
					
				}
			}
			 data = $.parseJSON(val);
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+data.item_name+'<input type="hidden"  id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+data.id+'" </td>';
			template+='<td style="white-space: nowrap;"><label id="lb_cu_qty_'+index+'"></label><input type="hidden" id="current_qty_'+index+'"  name="current_qty_'+index+'" value="'+data.qty+'" class="form-control"><input type="hidden" name="measure_'+index+'" id="measure_'+index+'" value="'+data.measure+'"/></td>'; 
			template+='<td><input type="text" id="qty_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_unit_'+index+'"  value="1" class="form-control"><input type="hidden" name="unit_label_'+index+'" id="unit_label_'+index+'" value="'+data.unit_label+'"/></td>'; 
			template+='<td><input type="text" id="qty_per_unit_'+index+'" onKeyup="TotalQty('+index+')" name="qty_per_unit_'+index+'"  value="0" class="form-control"><input type="hidden" id="qty_measure_'+index+'" name="qty_measure_'+index+'" onKeyup="" value="'+data.qty_perunit+'" class="form-control"></td>';
			template+='<td style="white-space: nowrap;"><label id="lb_remain_'+index+'"></label><input type="hidden" id="remain_qty_'+index+'" name="remain_qty_'+index+'" class="form-control"><input type="hidden" name="qty_'+index+'" id="qty_'+index+'" value="0"/></td>';
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
			//diferQTY(index);
			TotalQty(index);
			qty = $('#current_qty_'+index).val();
			cur_qty = fullMeanQty(index,qty);
			document.getElementById("lb_cu_qty_"+index).innerHTML = cur_qty;
        },
        error:function(e){
            alert(e);
            //$("#result").html('There is error while submit');
        }
    });
}
	
function fullMeanQty(index,qty){
	
	qty_measure = $('#qty_measure_'+index).val();
	unit_label = $('#unit_label_'+index).val();
	measure = $("#measure_"+index).val()
	if(qty_measure==0){
		qty_measure=1;
	}else{
		qty_measure = qty_measure;
	}
	//value = parseString(qty);
	var arrays = qty.split('.');
	unit_qty = arrays[0];
	qty_per_unit = arrays[1];
	total_qty_per_unit = Math.round((parseFloat(qty)*parseFloat(qty_measure)) - (parseFloat(unit_qty)*parseFloat(qty_measure)));
	
	if(unit_qty>0 && qty_per_unit>0){
		l_qty = unit_qty+" "+measure+" & "+total_qty_per_unit+" "+unit_label;
	}else if(unit_qty>0 && qty_per_unit<=0){
		l_qty = unit_qty+" "+measure;
	}else if(unit_qty<=0 && qty_per_unit>0){
		l_qty = total_qty_per_unit+" "+unit_label;
	}else{
		l_qty=0;
	}
	//alert();
	return l_qty;
}
function TotalQty(index){
		
		main_qty =$("#qty_unit_"+index).val();
		detail_qty =  $("#qty_per_unit_"+index).val();
		qty_measure = $("#qty_measure_"+index).val();
		qty = $('#current_qty_'+index).val();
		if(qty_measure==0){
			qty_measure=1;
		}else{
			qty_measure = qty_measure;
		}
		total_qty = parseFloat(main_qty) + (parseFloat(detail_qty)/parseFloat(qty_measure));
		
		if(total_qty>qty){
			alert("Damaged product Can't more than Current Qty!");
			$("#qty_unit_"+index).val(0);
			$("#qty_per_unit_"+index).val(0);
			$("#qty_unit_"+index).focus();
			$("#qty_"+index).val(0);
			document.getElementById('lb_remain_'+index).innerHTML='';
		}else{
			$("#qty_"+index).val(total_qty.toFixed(3));
		}
		doRemainQty(index);
	}
function doRemainQty(index){
	//alert(1);
	damaged_qty = $("#qty_"+index).val();
	cur_qty = $('#current_qty_'+index).val();
	remain_qty = parseFloat(cur_qty)-parseFloat(damaged_qty);
	$('#remain_qty_'+index).val(remain_qty.toFixed(3));
	remain_full = fullMeanQty(index,$('#remain_qty_'+index).val());
	document.getElementById('lb_remain_'+index).innerHTML= remain_full;
}
function deleteRecord(index,type) {
		if(type==1){
			var identity = $('#identity').val();
			var arrays = identity.split(',');
		}else{
			var identity = $('#identity_price').val();
			var arrays = identity.split(',');
		}
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		
		if(type==1){
			$('#identity').val(strings);
			$("#row_location_"+index).remove();
		}else{
			$('#identity_price').val(strings);
			$("#row_price_"+index).remove();
		}
		

		// total price
	}


function ShowPopupProduct(index){
	item_id = $("#item_id_"+ index).val();
	record_id = index;
	if(item_id==-1){
		ShowDialog(true);
        
	}
}

function AddLocation(index){
	var location_id= $("#location_id_"+index).val();
	var item_id = $("#item_id_"+ index).val();
	if(location_id==-1){
		     record_id = index;
		     AddNewLocation(true);
			 
	  }	
	else{
		$.ajax({
		        url: "<?php echo $url_getcurrentitem;?>",
		        type: "post",
		        data: {'item_id':item_id, 'location_id':location_id},
		        success: function(data){
		            //alert(data);
		            val = $.parseJSON(data);
		            $("#qty_before_"+ index).val(val.qty);
		        },
		        error:function(){
		           // alert("Please Product Name And Location");
		            $("#result").html('There is error while submit');
		        }
		    });
		}
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#txt_name").val();
	var pro_code = $("#item_code").val();
	var category_id = $("#category_id").val();
	var brand_id = $("#brand_id").val();
	var remark = $("#remark_order").val();
	validate_text('#txt_name');
	validate_text('#item_code');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'category_id':category_id,'brand_id':brand_id,'remark':remark},
	        success: function(data){
	           val = $.parseJSON(data);
	           $('#item_id_'+record_id).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	           $('#item_id_'+record_id).trigger("liszt:updated");
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#location_id_'+record_id).append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
            $('#location_id_'+record_id).trigger("liszt:updated");
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
</script>