<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:18cm !important; padding: 0px; margin-bottom:30px; ">
			<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		    display: table-footer-group;
		}
#pageFooter:after {
    counter-increment: page;
    content:"Page " counter(page);
    left: 0; 
    top: 100%;
    white-space: nowrap; 
    z-index: 20px;
    -moz-border-radius: 5px; 
    -moz-box-shadow: 0px 0px 4px #222;  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
}
	</style>
		<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top:0 auto;white-space:nowrap;">
			<tbody><tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" style="font-size: 10px;margin-bottom: 0px;"   >
						<tr>
							<td width="40%" valign="top" align="center">
								<img style="height:45px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br />
								<div style="font-size: 10px;font-family:'Khmer MEF2';text-align: center;width:100%;"><?php echo $tr->translate("COMPANY_CUSTOMER"); ?></div>
							</td>
							<td width="20%" align="center" valign="top" style=""><div style="font-size: 14px;font-family:'Khmer MEF2';">វិក្កយបត្រ</div>INVOICE
							</td>
							<td width="40%" valign="top">
								<div style="white-space: nowrap;"><?php echo $tr->translate("ADDRESS_COMPANY"); ?></div>
								លេខទូរសព្ទ<?php echo $tr->translate("TEL_COMPANY"); ?>
							</td>
						</tr>
					</table>
			    </td>
			</tr>
			<style>
			.bold{
				font-weight:bold;
				}
			.tablesorter td{font-family:'khmer os battambang' !important;}
			.one{line-height: 15px;}
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#footer {
			  display: table-footer-group;
			}
			@page {
			       @bottom-left {
			            content: counter(page) "/" counter(pages);
			        }
			     }
			@media print {
			    footer {page-break-after: always;}
			}
			</style>			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top">
					<table width="100%" style=" ;font-size: 11px;border: 1px solid #000;">
						<tbody><tr>
							<td width="100px;">&nbsp;ឈ្មោះអតិថិជន</td>
							<td width="1px"> :</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 11px;"><?php echo $rs['customer_name']?></label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :</td>
							<td><label id="lbl_phone" class="one"><?php echo $rs['contact_phone']?></label></td>
						</tr>
						<tr>
							<td>&nbsp;អាសយដ្ឋាន </td>
							<td> :</td>
							<td><label id="lbl_address" class="one"><?php echo $rs['address']?></label></td>
						</tr>
					</tbody></table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:2px;font-size: 11px;border: 1px solid #000;">
						<tbody><tr>
							<td width="90px;" style="white-space: nowrap;">&nbsp;លេខវិក្កយបត្រ</td>
							<td width="1px" style="padding-top:5px;">:</td>
							<td><label id="lb_invoice" class="one"><?php echo $rs['sale_no']?></label></td>
						</tr>
						<tr>
							<td>&nbsp;ថ្ងៃចេញ</td>
							<td colspan="1"> :</td>
							<td><div style="text-align:left;margin-top:-2px;font-size:10px; white-space: nowrap;"><?php echo date("d/m/Y",strtotime($rs['date_sold']));?></div></td>
						</tr>
						<tr>
							<td>&nbsp;អ្នកលក់</td>
							<td colspan="1"> :</td>
							<td>
								<div style="font-weight:bold;color:#000; font-size: 11px;font-family:'Khmer OS Battambang';margin-top: -3px;"><?php echo $rs['user_name']?></div>
							</td>
						</tr>
					</tbody></table>
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
						<tbody><tr>
							<td colspan="6" valign="top">
								<div id="t_amountmoneytype">
									<table class="collape tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr class="hearder_table" style="font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;"><td style="border:1px solid #000;font-size:12px;">លរ</td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ឈ្មោះមុខទំនិញ</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ចំនួនលក់</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ចំនួនថែម</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ចំនួនសរុប</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">តម្លៃរាយ</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">សរុប</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">បរិមាណ</strong></td>
												
											</tr>
										</thead>
										<tbody>
										<?php 
										$index=0;
										if(!empty($this->rsdetail)){foreach($this->rsdetail as $key => $item){ $index++;?>
										<tr style=" font-size:12px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $key+1;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo $item['pro_name'];?> </strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"><?php echo $item['qty_order'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $item['qty_detail'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $item['sub_total'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $item['price'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $item['sub_total'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $item['remark'];?></strong></td>
										</tr>
										<?php }
										if($rs['transport_fee']>0){?>
											<tr style=" font-size:12px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $key+1;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;ថ្លៃសេវាដឹកជញ្ជូន</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">1<?php //echo $item['qty_order'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">1<?php //echo $item['qty_order'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">1<?php //echo $item['qty_order'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $rs['transport_fee'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo $rs['transport_fee'];?></strong></td>
										</tr>
										<?php }}
										for($index;$index<=16;$index++){
										?>
										<tr style=" font-size:12px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $index+1;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
										</tr>
										<?php }?>
										<tr style="height:25px;;text-align:right;font-weight:bold;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="6"> <?php echo number_format($rs['all_total_riel'],3)?> រៀល&nbsp;</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">សរុប&nbsp;</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">$ <?php echo number_format($rs['net_total'],3)?> &nbsp;</td></tr>
											<tr style=" font-size:12px; text-align:right;font-weight:bold;">
											<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="6">- សូមពិនិត្យទំនិញអោយបានត្រឹមត្រូវ</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">បញ្ចុះតម្លៃ&nbsp;</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">$ <?php echo number_format($rs['discount_value'],3)?> &nbsp;</td></tr>
											<tr style=" font-size:12px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="6">- ទំនិញដែលទិញហើយមិនអាចប្តូរវិញបានទេ</td>
												<td style="border:1px solid #000;font-size:12px !important;"><strong style="color:#000;">សរុបដុល&nbsp;</strong></td>
												<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($rs['all_total'],3)?> </strong>&nbsp;</td>
											</tr>
											<tr style=" font-size:12px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000" colspan="6"></td>
												<td style="border:1px solid #000;><strong style=" color:#000;">ប្រាក់កក់&nbsp;</td>
												<td style="border:1px solid #000;><strong style=" color:#000;">$ <?php echo number_format($rs['paid'],3)?>&nbsp;</td>
											</tr>
											<tr style=" font-size:12px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000" colspan="6"></td>
												<td style="border:1px solid #000;font-size:12px !important;"><strong style="color:#000;">នៅខ្វះ&nbsp;</strong></td>
												<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($rs['balance'],3)?></strong>&nbsp;</td>
											</tr>
											</tbody>
										</table>
										</div>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table border="0" width="100%" style="font-size:12px; white-space:nowrap;line-height:15px;margin-top:3px;border-collapse:collapse;">
									<tbody><tr>
										<td colspan="4">
											<table width="100%" border="0" style="white-space:nowrap;border-collapse:collapse;font-size:12px;line-height:16px;">	
												<tbody><tr>
													<td width="25%" align="center">អតិថិជន</td>
													<td width="25%" align="center">អ្នកទទួល</td>
													<td width="25%" align="center">អ្នកដឹក</td>
													<td width="25%" align="center">អ្នកចេញទំនិញ</td>
												</tr>	
											</tbody></table>	
										</td>
									</tr>
								</tbody></table>
							</td>
						</tr>
					</tbody></table>
				</td>
			</tr>
		</tbody></table>
    </div>
    <div style="text-align: center;margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/sales/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុក/បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
</script>
   