<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DAILYWORK')); 
?>
<?php  $dailywork= $this->frm_dailywork;?>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("CONTACT_NOTE");?>
			</div>
			<div class="caption pull-right">
				<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'contact','action'=>'index')); ?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form id="frm" class="form-horizontal" method="post" action="" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Contact_Name")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("name");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Phone")?></label>
								<div class="col-md-8">
									<div class="input-icon right"><i class="fa fa-calendar"></i>
										<?php echo $dailywork->getElement("phone");?>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("CATEGORY_PRODUCT")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("category");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("DATE")?></label>
								<div class="col-md-8">
									<input class="form-control form-control-inline date-picker" id="start_date" name="start_date" value="<?php echo date("Y-m-d")?>"  type="text" >
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Note")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("note");?>
								</div>
							</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
						<a href="<?php echo $this->baseUrl();?>/dailywork/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
					</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>