<title>List User </title>
<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_new = $this->url(array(
		'module'=>'rsvacl',
		'controller'=>'user',
		'action'=>'add',
	));
	
	$form=$this->form;
	$formfilter=$this->formfilter;
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("LIST_OF_USER_IN_SYSTEM");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('location');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('user_type_filter');?></label>
						<label class="control-label col-md-2"><?php echo $formfilter->getElement('status_se');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>			
				</form> 
				<div class="contain_form" style="clear: both;">
						<?php echo  $this->form;?>
			    </div>
		   </div>
		</div>
	</div>
</div>