<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'other','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'other','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'other','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->Form;
	
	$rs = $this->rs;
?>
<title><?php echo $tr->translate("OTHER");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("OTHER_LIST");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('adv_search');?>
								</div>
												
								<div class="col-md-3">
									<?php echo $formFilter->getElement('type');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('status_search');?>
								</div>
								<div class="col-md-3">
									 <button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
				</div>
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						
						<div class="portlet-body">
							<table style="font-size: 12px;" class="table table-striped table-bordered table-hover" id="sample_2">
							<thead>
								<tr>
									<th><?php echo $tr->translate("NO");?></th>
									<th><?php echo $tr->translate("NAME");?></th>
									<th><?php echo $tr->translate("TYPE");?></th>
									<th><?php echo $tr->translate("STATUS");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody>
								<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
								<tr class="odd gradeX">
									<td><?php echo $key+1?></td>
									<td><?php echo $row["name_en"]?></td>
									<td class="center">
										<?php 
											if($row["type"]==2){
												$type = "Model";
											}elseif ($row["type"]==3){
												$type = "Size";
											}elseif ($row["type"]==4){
												$type = "Color";
											}elseif($row["type"]==6){
												$type = "Customer Type";
											}
											 echo $type;
										
										?>
									</td>
									<td>
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>
									
									<td>
										<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a>
										
									</td>
								</tr>
								<?php }}?>
							</tbody>
							</table>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->
	</div>
