<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'exchangerate','action'=>'index',));
	$url_delete = $this->url(array('module'=>'category','controller'=>'index','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("ការកំណត់ផ្សេងៗ");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ការកំណត់ផ្សេងៗ");?>
			</div>
			<div class="caption pull-right">
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
				</a>
			</div>
			
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Label");?></label>
								<div class="col-md-8">
									<input type="text" name="txt_label" id="txt_label" value="" class="form-control">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("តម្លៃ");?></label>
								<div class="col-md-8">
									<input type="text" name="txt_value" id="txt_value" value="" class="form-control">
								</div>
							</div>
							<div class="form-group">
								<div class="col-md-3"></div>
								<div class="col-md-2">
									<a href="<?php echo $this->baseUrl();?>/sales/exchangerate"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
								</div>
								<div class="col-md-2">
									<div class="input-icon right">
										<button type="submit" name="saveclose" value="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
									</div>
								</div>
								<div class="col-md-2">
								</div>
								<div class="col-md-3"></div>
							</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>