<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$url_submit =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'update-customer-order'));//for other verstion
	//$url_submit =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'abc'));
	$url_cancel =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'index'));
	$url_new =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'customer-order'));
	$rowLostItems = $this->rowsOrder;
	
?>
<title><?php echo $tr->translate("MENU_SALES_SALES_ORDER_UPDATE_CUSTOMER_ORDER");?></title>
<div class="wrapper">
    <div class="clear"></div>
    <div class="contance">
    </div><!--end of contance-->
    <div class="left">
    </div><!--end of left-->
    <div class="right">
    	<form id="frm" action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
    	<div class="contorl-cus">
        	<?php //echo $this->control ;?>
        	<?php  //$frmctrol=$this->control ;?>
        	<?php //echo $frmctrol->getElement('New');?>
        	<?php //echo $frmctrol->getElement('Update');?>
        	<?php //echo $frmctrol->getElement('Copy');?>
        	<?php //echo $frmctrol->getElement('Version');?>
        	<?php //echo $frmctrol->getElement('Deactive');?>
        	<!-- <a href="<?php echo $url_new ?>" class="new"><?php //echo $tr->translate("NEW");?></a>
        	<a href="<?php echo $url_cancel ?>" class="cancel"><?php //echo $tr->translate("CANCEL");?></a> -->
    		<input onclick="closeMe()" type="button" name='btn_close'  value="<?php echo $tr->translate("CLOSE");?>" class="close" />
        </div>
        <div class="style-form">
        	<div class="view-table" style="padding:20px;">
				<div class="head_form">
					<?php echo $tr->translate("Customer info");?>
				</div>
			   	<div class="contain_form shadow">
			   		    <table>
				                <tr><?php echo $form->getElement("id");?>
				                	<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
				                    <td width="30%"><?php echo $form->getElement("customer_id");?></td>
				                    <td><?php echo $tr->translate("LOCATION_NAME");?></td>
				                    <td width="30%"><?php echo $form->getElement("LocationId");?></td>
				                </tr>
				                <tr>
				                	<td><?php echo $tr->translate("DATE_ORDER");?></td>
				                    <td><?php echo $form->getElement("order_date"); ?></td>
				                     <td><?php echo ucwords($tr->translate("SALE_AGENT"));?></td>
				                    <td><div class="select_d"><?php echo $form->getElement("sales_ref"); ?></div></td>
				                </tr>
				                <tr>
				                	<td><?php echo $form->getElement("oldStatus");?></td>
				                    <td><?php echo $form->getElement("old_location");?></td>
				                    <td><?php echo $tr->translate("ORDER_NUMER");?><div id ="feedback"></div></td>
				                    <td><?php echo $form->getElement("order");?></td>
				                </tr>
				                 <tr>
				                	<td></td>
				                	<td></td>
				                    <td><?php //echo $tr->translate("STATUS");?></td>
				                    <td><?php //echo $form->getElement("status");?></td>
				                </tr>
				            </table>
			   	</div><!-- end of .contain_table -->
			   	
         	</div><!-- end of .view-table -->
         </div><!-- end of .style-form -->
         <div id="tabs" class="tabs-bottom">
			 <ul style="border-top:1px solid #999;">
			 	<li><a href="#tabs-1"><?php echo $tr->translate("CUSTOMER_ORDER");?></a></li>
			</ul>
		<div class="tabs-spacer"></div>
			<div id="tabs-1"> 
				<div class="head_form">
					<?php echo $tr->translate("CUSTOMER_ORDER_LIST");?>
				</div>
			   	<div class="contain_form">
								<div class="view-table">
			   						<table class="collape" id="order_item">
										<tr height="33px">
											<td class="sub-tdheader"><?php echo $tr->translate("DEL");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
											<td class="sub-tdheader" width="100px"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("QTY_ORDER_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("SUB_TOTAL_CAP");?></td>
										</tr>
									</table>
								</div>
								<table>
									<tr>
										<td class="new-row">
											<div class="btn">
												<button class="positive" type="button" id="new_item"  name= "new_followup" value="<?php echo $tr->translate("NEW");?>">
													&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
												</button>
											</div>
											<input type="hidden" id="identity" name="identity" />
										</td>
									</tr>
								</table>
								
				           <div class="view-table">
								<table style="width:95%; margin:0 auto;">
						                <tr>
						                	<td><?php echo $tr->translate("REMARK");?></td>
						                    <td><?php echo $tr->translate("PAID");?></td>
						                    <td><?php echo $form->getElement("paid");?></td>
						                </tr>
						                <tr>
						                    <td><?php echo $form->getElement("remark");?></td>
						                    <td><?php echo $tr->translate("BALANCE");?></td>
						                    <td width="30%"><?php echo $form->getElement("remain");?></td>
						                </tr>
						                 <tr>
						                    <td></td>
						                    <td colspan="2">
						                    	<input class="btn_submit" type="submit" name="payment" value="<?php echo  $tr->translate("UPDATE");?>" />
						                        <input class="btn_submit" type="submit" name="cancel_order" value="<?php echo  $tr->translate("CANCEL_ORDER");?>" />
						                    	<input id="btnCancel_frm" class="btn_submit" type="button" Onclick="Cancel()" value="<?php echo $tr->translate("Cancel");?>" />
						                    </td>
						                    
						                </tr>
						            </table>	
					       </div>
			   		</div><!-- end of .contain_table -->
				</div><!-- tab 1 -->	
			  </div>	
    	</form>
    </div><!-- end right -->
</div><!-- end wrapper -->
<!-- add customer -->
<div id="overlay-vendor" class="web_dialog_overlay"></div>
<?php $frm_customer= $this->form_customer;?>
		<div id="dialog-vendor" class="web_dialog">
		<form id="frmvendor">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_CUSTOMER");?>
				<a href="#" id="btnClosevendor" class="cancelDailog"></a>
			</div>
			<table style="width: 98%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td width="70px"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
					<td><?php echo $frm_customer->getElement("txt_name");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $frm_customer->getElement("txt_contact_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $frm_customer->getElement("customer_phone");?></td>
					<td><?php //echo $tr->translate("TYPE_PRICE_SM"); ?></td>
					<td ><?php // $frm_customer->getElement("price_type"); ?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("EMAIL");?></td>
					<td><?php echo $frm_customer->getElement('txt_mail');?></td>
					<td><?php echo $tr->translate("CUS_ADDRESS");?></td>
					<td><?php echo $frm_customer->getElement("txt_address");?></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td colspan="2">
						<input id="btn_add" Onclick="addNewCustomer()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancelVendor" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					
				</tr>
	       </table>
	     </form>
 </div>
  <!-- end new product -->
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_product= $this->form_product;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("ITEM");?></td>
					<td><?php echo $frm_product->getElement("product_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("ITEM_CODE");?></td>
					<td><?php echo $frm_product->getElement("item_code");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("PRICE");?></td>
					<td><?php echo $frm_product->getElement("item_price");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_product->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addProduct()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
 
<!-- and new location -->
<div id="overlay-location" class="web_dialog_overlay"></div>
		<?php $form_stock = $this->form_addstock; ?>
		<div id="dialog-location" class="web_dialog">
		<form id="frm-location">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_LOCATION");?>
				<a href="#" id="btnCloseLocation" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("LOCATION_NAME");?></td>
					<td><?php echo $form_stock->getElement("StockName");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $form_stock->getElement("ContactName");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $form_stock->getElement("ContactNumber");?></td>
					<td><?php echo $tr->translate("STOCK_ADD");?></td>
					<td><?php echo $form_stock->getElement("location_add");?></td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $form_stock->getElement("description");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewLocation()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btncancel_location" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					<td colspan="2"></td>
				</tr>
	       </table>
	     </form>
 </div>
 
 <!-- for popup sale agent -->
 <?php $frm_agent = $this->form_agent; ?>
 <div id="agent_popup" class="web_dialog_overlay"></div>
		
		<div id="dialog_popup" class="web_dialog">
		<form id="frm-agent">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_AGENT");?>
				<a href="#" id="cancelDailogAgent" class="cancelDailog"></a>
			</div>
			<table style="width: 100%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("AGENT_NAME");?></td>
					<td><?php echo $frm_agent->getElement("agent_name");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $frm_agent->getElement("contact_phone");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("POSITION");?></td>
					<td><?php echo $frm_agent->getElement("positon");?></td>
					<td><?php echo $tr->translate("STOCK_ADD");?></td>
					<td><?php echo $frm_agent->getElement("brand_name");?></td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_agent->getElement("desc_agent");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewAgent()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btncancel_agent" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					<td colspan="2"></td>
				</tr>
	       </table>
	     </form>
 </div>
<script type="text/javascript">
jQuery(document).ready(function(){
	$("#customer_id").chosen();
	var index5 = '<?php echo count($rowLostItems);?>';
	var option5 = '<?php echo $this->itemsOption; ?>';
	var baseUrl = '<?php echo BASE_URL; ?>';
	var template = '';
	// add Item
	$('#new_item').click(function(){
		index5++;
		//var inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="">';
    	
		template='<tr id="row_order_'+index5+'" style="height:33px;">';
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		template+='<td class="quater-input" width="3%">'+index5+'</td>';
		template+='<td class="quater-input" width="30%"><select onChange="getCurrentPrice('+ index5 +');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select></td>';
		template+='<td class="quater-input"><input type="text" onBlur="getPriceByQty('+index5+')" class="validate[required,custom[number]] input" id="qty'+index5+'" name="qty'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]] input" id="price'+index5+'" name="price'+index5+'"/></td>';
		template+='<td class="quater-input"><input type="text" class="input" readonly="readonly" onBlur="calculatePrice('+index5+')" id="total'+index5+'" name="total'+index5+'" /></td>';
		template+="</tr>";
		$('#order_item').append(template);
		var preIdentity = $('#identity').val();
		$('#identity').val(preIdentity+','+index5);
		$("#lostItemFrm").validationEngine();
		$("#item_id_"+index5).chosen();
	});

	initList();
	$('#lostItemFrm').validationEngine();
});

//show row of order item
function initList() {
	var template;
	var optionItem = '<?php echo $this->itemsOption;?>';
	<?php if(!empty($rowLostItems)) {
		foreach($rowLostItems AS $i=>$r){
			$inx = $i +1;?>
			template='<tr id="row_order_<?php echo $inx;?>" style="height:33px;">';
			if(<?php echo $inx;?> == 1) {
			template+='<td class="quater-input"></td>';
			} else {
			template+='<td class="quater-input"><img onClick="deleteRecord(<?php echo $inx;?>)" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			}
			template+='<td class="quater-input" width="3%"><?php echo $inx;?></td>';
			template+='<td class="quater-input" width="30%"><select onChange="getCurrentPrice(<?php echo $inx;?>);"  id="item_id_<?php echo $inx;?>" name="item_id_<?php echo $inx;?>" >'+optionItem+'</select></td>';
			template+='<td class="quater-input"><input class="validate[required,custom[number]]" onBlur="getPriceByQty(\'<?php echo $inx;?>\')" type="text" id="qty<?php echo $inx;?>" name="qty<?php echo $inx;?>"/></td>';
			template+='<td class="quater-input"><input onBlur="calculatePrice(\'<?php echo $inx;?>\')" type="text" class="validate[required,custom[number]] input" id="price<?php echo $inx;?>" name="price<?php echo $inx;?>"/></td>';
			template+='<td class="quater-input"><input type="text" class="input" readonly="readonly" id="total<?php echo $inx;?>" name="total<?php echo $inx;?>" /></td>';
			//template+='<td class="quater-input"><input type="radio" onChange="calculatePrice(\'<?php echo $inx;?>\')" name="dis-type-<?php echo $inx;?>"  id="dis-type1-<?php echo $inx;?>" value="2" />Fix Value &nbsp;<input type="radio" onChange="calculatePrice(\'<?php echo $inx;?>\')" name="dis-type-<?php echo $inx;?>" id="dis-type2-<?php echo $inx;?>" value="1" />% &nbsp;<input type="text"  onChange="calculatePrice(\'<?php echo $inx;?>\')" class="input70px input" id="dis-value<?php echo $inx;?>" name="dis-value<?php echo $inx;?>" /> =<input type="text" readonly="readonly" class="input70px input" id="real-value<?php echo $inx;?>" name="real-value<?php echo $inx;?>" /></td>';
			//template+='<td class="quater-input"><input class="input100px input" readonly="readonly" type="text" id="after_discount<?php echo $inx;?>" name="after_discount<?php echo $inx;?>"/></td>';
			template+='</tr>';
			$('#order_item').append(template);

			$('#item_id_<?php echo $inx;?>').val('<?php echo $r['pro_id'];?>');
		
			$('#price<?php echo $inx;?>').val('<?php echo $r['price'];?>');
			$('#qty<?php echo $inx;?>').val('<?php echo $r['qty_order'];?>');
			$('#total<?php echo $inx;?>').val('<?php echo $r['total_befor']; ?>');
		//	if(<?php echo $r['disc_type'];?> == 1) {
		//		$('#dis-type2-<?php echo $inx;?>').attr("checked", "checked");
		//	}else {
		//		$('#dis-type1-<?php echo $inx;?>').attr("checked", "checked");
		//	}
			
		//	$('#dis-value<?php echo $inx;?>').val('<?php echo $r['disc_value'];?>');
			// calculate discount and after discount
		//	var dis_type = <?php echo $r['disc_type'];?>;
		//	var dis_value = <?php echo $r['disc_value'];?>;
		//	var total = <?php echo $r['qty_order'] * $r['price'];?>;
		//	var discountReal = 0;
		//	if(dis_value > 0) {
		//		discountReal = (dis_type == 1)? (total * dis_value) / 100 : dis_value;
		//	}
			//var afterTotal = total - discountReal;
		//	$('#real-value<?php echo $inx;?>').val(discountReal);
		//	$('#after_discount<?php echo $inx;?>').val(afterTotal);
			$('#item_id_<?php echo $inx;?>').chosen(); 
			if(<?php echo $inx;?>!=1) {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+<?php echo $inx;?>);
			} else {$('#identity').val(<?php echo $inx;?>);}
		<?php } }?>
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

	// total price
	netTotal();
	doTotal();
}

//Calculate price of order
function calculatePrice(index) {
	// total price
	var price = $('#price'+index).val();
	var qty = $('#qty'+index).val();
	var total = price * qty;
	$('#total'+index).val(total);

	// discount of total price
	var disType = $('input:radio[name=dis-type-'+index+']:checked').val();
	var disValue = ($('#dis-value'+index).val() == '')? 0 : $('#dis-value'+index).val();
	var discount = (disType == 1)? total * disValue / 100 : disValue;
	$('#real-value'+index).val(discount);
	var lastTotal = $('#total'+index).val() - discount;
	$('#after_discount'+index).val(lastTotal);
	// total price
	netTotal();
	doTotal();
}
function doTotal() {
	var discountType = $('input:radio[name="discount_type"]:checked').val();
	var discountValue = ($('#discount_value').val() == '')? 0 : $('#discount_value').val();
	var netTotal = ($('#net_total').val()=='')?0 : $('#net_total').val();
	var discountReal = 0;
	discountReal = (discountType == 1)? (netTotal * discountValue) / 100 : discountValue;
	$('#discount_real').val(discountReal);
	var allTotal = Number(netTotal)-Number(discountReal);
	$('#all_total').val(allTotal);
	$('#remain').val(allTotal)-$('#paid').val();
}
function doRemain() {
	// total for all record(total part)
	var total = $('#all_total').val();
	var paid = $('#paid').val();
	var remain = total-paid;
	$('#remain').val(remain);
}
function netTotal() {
	// total for all record(total part)
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#after_discount'+rowIDArray[n]).val());
	}
	$('#net_total').val(netTotal);
}
</script>
<?php $url_getcurrentitem =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-customer-info')); ?>
<script>
function getCustomerInfo(){
	var customer_id = $("#customer_id").val();
	if(customer_id==-1){
		  ShowVendorDialog(true);
		 
    }
	else{
		$.ajax({
	        url: "<?php echo $url_getcurrentitem;?>",
	        type: "post",
	        data: {'customer_id':customer_id},
	        success: function(data){
	            val = $.parseJSON(data);
	            $("#contact").val(val.contact_name);
	            $("#txt_phone").val(val.phone);
	            $("#remark_add").val(val.address);
	        },
	        error:function(){
	           // alert("Please Select Vendor");
	            $("#result").html('There is error while submit');
	        }
	    });
	}
}
//for get current price
<?php $url_getcurrent_price =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-current-price')); ?>
var record_index = 1;
function getCurrentPrice(index){
	item_id = $("#item_id_"+ index).val();
	//customerid = $("#customer_id").val();
	if(item_id==-1){
		     record_index = index;
			 ShowDialog(true);
	}
	else{
		qty = $("qty"+index).val();
		if(qty!=="" || qty!==null){
				getPriceByQty(index);
		}
	}
	
}

<?php $url_current_price =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-current-price')); ?>
function getPriceByQty(index){
	item_id = $("#item_id_"+ index).val();
	qty = $("#qty"+ index).val();

	$.ajax({
        url: "<?php echo $url_current_price;?>",
        type: "post",
        data: {'item_id':item_id,'qty':qty},
        success: function(data){
            val = $.parseJSON(data);
            if(parseInt(val.price)==0){
           	 	alert("Price of quantity order is not set price or out of rang!\n\n Please Check it again!");
             }
           
            $("#price"+ index).val(val.price);
           //$("#qty"+ index).val(1);
            calculatePrice(index);
        },
        error:function(){
            $("#result").html('There is error while submit');
        }
    });
}

function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		     AddNewLocation(true);
	  }	
}
//for add new vendor 
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	var customer_name  = $("#txt_name").val();
	var contact = $("#txt_contact_name").val();
	var price_type = $("#price_type").val();
	var phone   = $("#customer_phone").val();
	var address = $("#txt_address").val();
	var txt_mail= $("#txt_mail").val();
	validate_text('#txt_name');
	$.ajax({
        url: "<?php echo $url_add_customer;?>",
        type: "post",
        data: {'customer_name':customer_name,'contact':contact,'price_type':price_type,'phone':phone,'address':address,'txt_mail':txt_mail},
        success: function(data){
            val = $.parseJSON(data);           
            $('#customer_id').append($("<option></option>").attr("value",val['cus_id']).attr("selected",true).text(customer_name));
         //  $('#customer_id').next().val(customer_name);
            $('#customer_id').trigger("liszt:updated");
            document.getElementById("frmvendor").reset();
            HideDialogVendor();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
//for add location
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
           $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
           $('#LocationId').next().val(location_name);
           
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
 
}
//add new product 
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#product_name").val();
	var pro_code = $("#item_code").val();
	var price = $("#item_price").val();
	var remark = $("#remark_order").val();
	validate_text('#product_name');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'price':price,'remark':remark},
	        success: function(data){
	            val = $.parseJSON(data);
	            $('#item_id_'+record_index).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name));  
	            $('#item_id_'+record_index).trigger("liszt:updated");;
	             document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}

//for submit sale agent
<?php $url_add_agent =  $this->url(array('module'=>'sales','controller'=>'sale-agent','action'=>'add-agent')); ?>
function addNewAgent(){
	var agent_name = $("#agent_name").val();
	var phone = $("#contact_phone").val();
	var positon = $("#positon").val();
	var location = $("#brand_name").val();
	var desc = $("#desc_agent").val();
	validate_text('#agent_name');
	$.ajax({
        url: "<?php echo $url_add_agent;?>",
        type: "post",
        data: {'agent_name':agent_name,'phone':phone,'positon':positon,'location':location,'desc':desc},
        success: function(data){
           val = $.parseJSON(data);

           $('#sales_ref').append($('<option></option>').attr('value',val['agent_id']).attr("selected",true).text(agent_name)); 
           HideAgentDialog();
           document.getElementById("frm-agent").reset();
           
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
 
}
//function Cancel(){
//	window.open("<?php //echo BASE_URL;?>/sales/sales-order/index","_parent");
//}
function showAgentPopup(){
	var sale_agent = $("#sales_ref").val();
	if(sale_agent==-1){
		showAgentDialog(true);
	}
}

function showAgentDialog(modal)
{
    $("#agent_popup").show();
    $("#dialog_popup").fadeIn(300);

    if (modal)
    {
        $("#agent_popup").unbind("click");
    }
    else
    {
        $("#agent_popup").click(function (e)
        {
            HideAgentDialog();
        });
    }
}
function HideAgentDialog()
{
    $("#agent_popup").hide();
    $("#dialog_popup").fadeOut(300);
}
function Cancel(){
		var comfir= confirm("តើលោកអ្នកពិតជាចង់ចាកចេញរឺ ? ");
		if(comfir==true){
			window.open("<?php echo BASE_URL;?>/sales/sales-order/index","_parent");
		}
}
</script>
