<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));
?>
<title><?php echo $tr->translate("ADD_PURCAHSE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_ORDER")?>
				</div>
				<div class="tools">
					<label><a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i><?php echo $tr->translate("GO_BACK");?></button></a></label>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id='frm' autocomplete="off" class="form-horizontal" novalidate="novalidate" action="<?php echo $url_submit; ?>" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("VENDOR_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("v_name");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("LOCATION_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('LocationId');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ORDER_DATE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<i class="fa fa-calendar"></i><?php echo $form->getElement("order_date");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php  echo $tr->translate("DATE_IN");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<?php echo $form->getElement("date_in");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PO_NUM");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("txt_order"); ?></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_NO");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("invoice_no"); ?></div>
							</div>
						</div>
						<div class="form-group" >
							<div style="opacity:0;pointer-events: none;">
							<label class="control-label col-md-2"><?php echo $tr->translate("STATUS");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("status");?>
								</div>
							</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
						</div>
						<div class="form-group">
						<div class="col-md-12">
							<label class="control-label col-md-1 col-lg-1">
								<button type="button" class="btn red delete col-md-12">
									<i class="fa fa-barcode"></i>
									<span>Scan </span>	
								</button>
							</label>
							<label class="control-label col-md-8">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();" >
								<?php echo $this->items; ?>
								</select>
							</label>
							<label class="control-label col-md-2 col-lg-2 col-sm-12">
								<button type="button" onclick="popupProduct();" class="btn red delete col-md-12">
									
									<span>&nbsp;&nbsp;បន្ថែមមុខទំនិញថ្មី</span>
								</button>
							</label>
							<label class="control-label col-md-1 col-lg-1 col-sm-12">
								<button type="button" class="btn red delete col-md-12">
									<input type="checkbox" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;Free</span>
								</button>
							</label>
						</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th><?php echo $tr->translate("FREE");?></th>
									<th><?php echo $tr->translate("QTY_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
									<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
						<div class="form-group">
						   <label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_name");?>
								</div>
							</div>
							<div class="col-md-1">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_number");?>
								</div>
							</div>
							<label class="control-label col-md-1"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required">
							* </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("totalAmoun");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("បញ្ចុះតម្លៃ");?>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("dis_value");?>
								    <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ថ្ងៃត្រូវចេញសែក");?>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php //echo $form->getElement("date_issuecheque");?>
								</div>
							</div>
							<label class="control-label col-md-2">កម្រៃ/កម្រៃរ៉ាប់រង​​
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("commission");?>
								</div>
							</div>
							<label class="control-label col-md-2"​ >ថ្លៃដឹកជញ្ជួន/ផ្សេងៗ​ 
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("commission_ensur");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							 <label class="control-label col-md-2"><?php //echo $tr->translate("CURRENCY_TYPE");?><span class="required">
								 </span>
							</label>
							<div class="col-md-3">
								<div class="input-icon right">
									<?php //echo $form->getElement("currency");?>
								</div>
							</div>
							<label class="control-label col-md-1" style="text-align: center;white-space: nowrap;">ឈ្មោះធនាគារ </label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("bank_name");?>
								</div>
							</div>
							<label class="control-label col-md-2">សរុបទាំងអស់​
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								<?php echo $form->getElement("all_totalpayment");?>
								</div>
							</div>
						</div>
						<div class="form-group">
						<label class="control-label col-md-2">
						</label>
						<div class="col-md-3">
						</div>
							<label class="control-label col-md-1"><?php echo $tr->translate("ប្រាក់បានបង់");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("ជំពាក់");?><span class="required">
							* </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								<?php echo $form->getElement("remain");?>
								</div>
							</div>
						</div>
						<div class="form-group">
						    <div class="col-md-3"></div>
						    <div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/purchase/index/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-2">
								<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							<div class="col-md-3"></div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('#frm').submit(function() {
	customer_id=$("#v_name").val();
	if(customer_id=='' || customer_id==-1){
		alert("Please select vendor name");
		$('#v_name').select2('open');
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("Please add product row");
		$('#add_item').select2('open');
		return false;
	}
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;	    
	}
});
</script>
<?php $frm_product= $this->form;?>
<div id="productpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_PRODUCT");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php //echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmproduct" name="frmproduct" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PRODUCT_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("name");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<span class="required">
							        <?php echo $tr->translate("ITEM_CODE");?>
						    </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("pro_code");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("BARCODE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("barcode");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SERIAL_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("serial");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PRODUCT_CATEGORY");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("category");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("BRAND_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("brand");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php //echo $tr->translate("MODEL");?>
								<span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php //echo $frm_product->getElement("model");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COLOR");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("color");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SIZE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("size");?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("MESUER_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("measure");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("qty_unit");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("MEASURE_LABEL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<?php echo $frm_product->getElement('label');?>
							</div>
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("NOTE");?><span class="required">
								</span>
							</label>
							<div class="col-md-10">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("description");?>
								</div>
							</div>
						</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" Onclick="addProduct();" class="btn bt-bg btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
						</label>
					</div>
				</div>
				</form>
			   </div>
		     </div>
	        </div>
          </div>
          </div>
        </div>
    </div>
 </div> 
<?php $frm_vendor= $this->form_vendor;?>
<div id="dialogvendor" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
					<div class="col-md-12">
						<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="icon-home"></i><?php echo $tr->translate("MENU_PURCHASE_VENDOR_ADD");?>
							</div>
							<div class="caption pull-right">
								<a href="<?php //echo;?>" >
									 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
								</a>
							</div>
						</div>
						<div class="portlet-body form">
								<form id="frmvendor" name="frmvendor" class="form-horizontal" enctype="multipart/form-data" method="post">
                                            <div class="form-body">
                                               	 <div class="form-group">
	                                               	<label class="control-label col-md-3"><?php echo $tr->translate("VENDOR_NAME");?></label>
                                                <label class="control-label col-md-9"><?php echo $frm_vendor->getElement("vendor_name");?></label>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("COM_PHONE");?></label>
                                                    <label class="control-label col-md-3"><?php echo $frm_vendor->getElement("com_phone");?></label>
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("CON_NAME");?></label>
                                                    <label class="control-label col-md-3"><?php echo $frm_vendor->getElement("txt_contact_name");?></label>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("CON_NUM");?></label>
                                                    <label class="control-label col-md-3"><?php echo $frm_vendor->getElement("v_phone");?></label>
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("EMAIL");?></label>
                                                    <label class="control-label col-md-3"><?php echo $frm_vendor->getElement("txt_mail");?></label>
                                                </div>
                                                 <div class="form-group">
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("VENDOR_ADD");?></label>
                                                    <label class="control-label col-md-9"><?php echo $frm_vendor->getElement("txt_address");?></label>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label col-md-3"><?php echo $tr->translate("NOTE");?></label>
                                                    <label class="control-label col-md-9"><?php echo $frm_vendor->getElement("vendor_note");?></label>
                                                </div>
                                               <div class="form-group">
                                                	<label class="control-label col-md-4"></label>
                                                	<label class="control-label col-md-4">
                                                		<button type="button" onclick="addNewVendor();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
													</label>
													<label class="control-label col-md-4"></label>
                                               </div>
                                            </div>
                               </form>
						</div>
					</div>
				</div>
			</div>
          </div>
        </div>
    </div>
 </div>	
<script>
function getSuppliyer(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
<?php $url_add_vendor =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'addvendor')); ?>
function addNewVendor(){
	var v_name  = $("#vendor_name").val();	
	if(v_name==''){
		return false;
	}	
	$.ajax({
        url: "<?php echo $url_add_vendor;?>",
        type: "post",
        data: $('#frmvendor').serialize(),
        success: function(data){
			alert(222);
            val = $.parseJSON(data);
		      val = $.parseJSON(data);
		    $('#v_name').append($("<option></option>").attr("value",val['vid']).attr("selected",true).text(v_name));                       
			$("#v_name").select2();
		    $('#dialogvendor').modal('hide');
        },
        error:function(e){
            alert("faile insert");
        }
    });
}
function popupProduct(){
	$('#productpopup').modal('show');
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-newproudct')); ?>
function addProduct(){
		branch_id = $("#LocationId").val();
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: $('#frmproduct').serialize()+'&'+$.param({ 'branch_id': branch_id}),
	        success: function(data){
		      data = $.parseJSON(data);
		      $('#add_item').append($("<option></option>").attr("value",data['pro_id']).attr("selected",true).text($("#name").val()));                       
			  $("#add_item").select2();
		      $('#productpopup').modal('hide');
			  addRow(data['pro_id']);
			  $('#item_id_'+index5).append($("<option></option>").attr("value",data['pro_id']).attr("selected",true).text($("#name").val()));                       
				 $("#item_id_"+index5).select2();
				 $('#qty'+index5).val(1);
	        },
	        error:function(err){
	           alert(err);
	        }
	    });	
}
var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=1;
function addRow(item_id) {
	index5++; //var first = index5;
	index=index+1;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index5+'</td>';
	template+='<td width="30%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<td ><input type="checkbox" onkeyup="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/> </td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /><input type="hidden"  class="input form-control" id="qty_detail_'+index5+'" name="qty_detail_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);
	getQtyById(index5);
	if(free.checked){
		$("#pricefree_"+index5).attr({checked:'checked'});  
		$("#price"+index5).val(0);
		$("#price"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).val(0);
	}
	else{
		$('#global_disc').val(0);
		$("#paid").val(0);
	}
	 $("#item_id_"+index5).select2();
	$("#row_order_0").remove();
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){//use
				item_id=$("#item_id_"+index).val();
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();
				branch_id = $("#LocationId").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							item_qty = $.parseJSON(data);										
							$("#qty_detail_"+index).val(item_qty.qty_perunit);
							main_qty =$("#qty_unit_"+index).val();
							detail_qty =  $("#qty_per_unit_"+index).val();
							$("#current_qty"+index).val(item_qty.qty);
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty"+index).val(total_qty.toFixed(3));
						},
						error:function(e){
							alert("err product"+e);
						}
				});
			}
}
function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		$('#productpopup').modal('show');
	}else{
		addRow(item_ids);
		$("#add_item").val("");
	}
}
var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var cur_type = 1;//$('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = $('#dis_value').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
		doRemain();
		sumincludeTransfer();
		doRemain();
}
function sumincludeTransfer(){
	commission = $("#commission").val();
if(commission==''){commission=0;};
	commission_ensur = $("#commission_ensur").val();
	if(commission_ensur==''){commission_ensur=0;}
	all_total = $("#all_total").val();
	if(all_total==''){all_total=0;}
	total=parseFloat(commission)+parseFloat(commission_ensur)+parseFloat(all_total);
	$('#paid').val(0);
	$("#all_totalpayment").val(total);
	$('#remain').val(total);
}
function CalcualteTax() {
	$('#status').val();
}
function doRemain() {
	var all_total = parseFloat($('#all_total').val());
	all_total = Number(all_total);
	var paid = parseFloat($('#paid').val());
	paid = Number(paid);
	if(isNaN(paid)){paid=0;}
	
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		$('#remain').val(all_total.toFixed(2));
   }else{
	   remain = parseFloat(all_total)-parseFloat(paid);
	   $('#remain').val(remain.toFixed(2));
	}
}
function totalQty(index){
	qtymain = $("#qty_unit_"+index).val();
	if(qtymain==''){qtymain=0;}
	qty_per_unit_ = $("#qty_per_unit_"+index).val();
	if(qty_per_unit==''){qty_per_unit=0;}

	qty_detail = $("#qty_detail_"+index).val();//detail
	if(qty_detail==''){qty_detail=0;}
	
	qty_buy = parseFloat(qtymain) + parseFloat(qty_per_unit_/(qty_detail));
	$('#qty'+index).val(qty_buy);	
	calculatePrice(index);	
}
function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));		
		}
		netTotal();
}
 var record_id = 1;
function ShowPopupProduct(product_id){
	item_id = $("#item_id_"+ product_id).val();
	record_id = product_id;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(product_id);
		calculatePrice(product_id);
	}
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		$('#popup_location').modal('show');
	  }	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
<?php $url_code =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'check-purchaseno')); ?>
function CheckPOInvoice(){
	pur_no=$("#txt_order").val();
	if(pur_no=="" || pur_no ==null){
		return false;
	}
	else{
	$.ajax({
			url:"<?php echo $url_code;?>",
			type:"post",
			data:{'pur_no':pur_no},
			success: function(data){
				value = $.parseJSON(data);
				if(value=="" || value==null){
				}
				else{
					alert("Invoice number is exist !");
					$("#txt_order").css("border-color","red");
					$("#txt_order").val("");
				}
			},
			error:function(){
			}
		});
	}	
}
</script>	