<title>Add Purchase Order</title>
<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add-purchase'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));
	$add_vendor = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add'));
?>
<div class="wrapper">
    <div class="clear"></div>
    <div class="left">
    	
    </div><!--end of left-->
    <div class="right">
    	<form id="orderFrm" action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
    	<div class="contorl-pro">
        	<?php  $frmctrol=$this->control ;?>
        	<?php echo $frmctrol->getElement('New');?>
        	<?php echo $frmctrol->getElement('Save');?>
        	<?php echo $frmctrol->getElement('Copy');?>
        	<?php echo $frmctrol->getElement('Version');?>
        	<?php echo $frmctrol->getElement('Deactive');?>
        	<?php echo $frmctrol->getElement('Attact');?>
        	<a href="<?php echo $url_cancel ?>" class="cancel"><?php echo $tr->translate("Cancel");?></a>
    		
        </div>
         <div id="tabs" class="tabs-bottom">
			<ul>
				<li><a href="#tabs-1">Product Info</a></li>
				<li><a href="#tabs-2">Order History</a></li>
			</ul>
			<div class="tabs-spacer"></div>
			<div id="tabs-1">
				<div class="style-form">
		        <div class="view-table">
		        <table style="width:100%; margin:0 auto;">
		                <tr>
		                	<td width="15%"><?php echo $tr->translate("Vendor Name");?></td>
		                    <td width="20%">
		                       <?php echo $form->getElement("v_name");?>                       
		                        <div id='userInfo'></div>
				   			        <input type="button" id="btnShowModal" value="" class="add-icon" />  
								    <div id="overlay" class="web_dialog_overlay"></div>
								    <div id="dialog" class="web_dialog">
								        <table style="width: 100%; border: 0px;" cellpadding="3" cellspacing="0">
								            <tr>
								                <td class="web_dialog_title" align="center">Do You to Add?</td>
								                <td class="web_dialog_title align_right">
								                    <a href="#" id="btnClose">Close</a>
								                </td>
								            </tr>
								            <tr>
								                <td colspan="2" style="text-align: center;">
								                    <input id="btnSubmit" type="button" value="Add New" />
								                    <input id="btnCancel" type="button" value="Cancel" />
								                </td>
								            </tr>
								        </table>
								    </div>
		                    </td>
		                    <td width="15%"><?php echo $tr->translate("Location");?></td>
		                    <td><?php echo $tr->translate("Order #");?>
		                    	<div id = "feedback">
						        </div>
		                    </td>
		                    <td width="15%"><?php echo $form->getElement("txt_order"); ?></td>
		                </tr>
		                <tr>
		                	<td width="15%"><?php echo $tr->translate("Contact");?></td>
		                    <td width="20%">
		                       <?php echo $form->getElement('contact'); ?>
		                    </td>
		                    <td width="15%"><?php echo $form->getElement("LocationId");?></td>            
		                    <td><?php echo $tr->translate("Order Date :");?></td>
		                    <td><?php echo $form->getElement("order_date");?></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("Phone");?></td>
		                    <td><?php echo $form->getElement("txt_phone"); ?></td>
		                    <td></td>
		                    <td><?php echo $tr->translate("Status");?></td>
		                    <td><?php echo $form->getElement("status");?></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("Vendor Address");?></td>
		                    <td><textarea disabled name="vendor_address" id="vendor_address" rows="3" cols="19"></textarea></div></td>
		                    <td>
		                    	<div id='user'></div>
				   			        <input type="button" id="btnShow" value="" class="add-icon" />  
								    <div id="overlay" class="web_dialog_overlay"></div>
								    <div id="dialog" class="web_dialog">
								        <table style="width: 100%; border: 0px;" cellpadding="3" cellspacing="0">
								            <tr>
								                <td class="web_dialog_title" align="center">Do You to Add?</td>
								                <td class="web_dialog_title align_right">
								                    <a href="#" id="btnClose">Close</a>
								                </td>
								            </tr>
								            <tr>
								                <td colspan="2" style="text-align: center;">
								                    <input id="ADD" type="button" value="Add1 New" />
								                    <input id="btnCancel" type="button" value="Cancel" />
								                </td>
								            </tr>
								        </table>
								    </div>		                    
		                    </td>
		                    <td width="20%">
		                    <td></td>
		                </tr>
		                 
		            </table>
		         </div>
		       </div>
		        <fieldset>
					<legend><?php echo $tr->translate("ADD-CUSTOMER-ORDER");?></legend>
					<table>
						<tr>
							<td valign="top" colspan="2">
								<table class="collape" id="table_order">
									<tr>
										<td class="sub-tdheader"><?php echo $tr->translate("DEL");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("ITEM-NAME");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("QTY-ORDER");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("UNIT PRICE");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("TOTAL-PRICE");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("DISCOUNT");?></td>
										<td class="sub-tdheader"><?php echo $tr->translate("SUB TOTAL");?></td>
									</tr>
								</table>
								<input type="hidden" id="identity" name="identity" />
								<table>
									<tr>
										<td class="new-row">
											<div class="btn">
												<button class="positive" type="button" id="new_item"  name= "new_followup" value="New">
													&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
												</button>
											</div>
										</td>
									</tr>
								</table>
								<table class="detail_table">
									<tr>
										<td class="total_label"><?php echo $tr->translate("NET-TOTAL");?></td>
										<td class="total_price"><?php echo $form->getElement('net_total');?></td>
									</tr>
									<tr>
										<td class="total_label"><?php echo $tr->translate("DISCOUNT");?></td>
										<td class="total_price"><?php echo $form->getElement('discount_type').$form->getElement('discount_value').' = '.$form->getElement('discount_real');?></td>
									</tr>
									<tr>
										<td class="total_label"><?php echo $tr->translate("ALL-TOTAL");?></td>
										<td class="total_price"><?php echo $form->getElement('all_total');?></td>
									</tr>
							</td>
						</tr>
					</table>
			   </fieldset>
			   <div class="view-table">
					<table style="width:100%; margin:0 auto;">
		                <tr>
		                	<td width="15%"><?php echo $tr->translate("Payment Method");?></td>
		                    <td width="20%">
		                    	<?php echo $form->getElement("payment_name");?>
		                    </td>
		                    <td width="12%"></td>
		                    <td width="30%">
		                       
		                    </td>
		                    <td></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("Pricing/Currency");?></td>
		                    <td>
		                    	<?php echo $form->getElement("currency");?>
		                    </td>
		                    <td width="20%" rowspan="3"></td>              
		                    <td><?php echo $tr->translate("Paid");?></td>
		                    <td><?php echo $form->getElement("paid");?></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("Remark");?></td>
		                    <td rowspan="2"><?php echo $form->getElement("remark");?></td>

		                    <td><?php echo $tr->translate("Total");?></td>
		                    <td><?php echo $form->getElement("remain");?></td>
		                </tr>
		                <tr>
		                    <td></td>
		                    <td><input type="submit" value="payment" name="payment" /></td>
		                    <td></td>
		                </tr>
		            </table>	
		         </div>			
			</div><!-- end tab1 -->
			<div id="tabs-2">
			
			</div><!-- end of tab2 -->
		</div><!-- end of main tab -->	
    	</form>
    </div><!-- end right -->
</div><!-- end wrapper -->
<script>
//action when click on add/delete of followup
var index5 = 0;
var option5 = '<?php echo $this->items; ?>';

var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var urlPrice = '<?php echo BASE_URL.'/distributor/order/getItemPrice'; ?>';
// add order record
function addRow() {
	index5++;
	template='<tr id="row_order_'+index5+'">';
	if(index5 == 1) {
		template+='<td class="quater-input">&nbsp;</td>';
	} else {
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td class="quater-input"><select id="item_id_'+index5+'" class="input200px" name="item_id_'+index5+'" >'+option5+'</select></td>';
	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" style="width: 70px;" class="validate[required,custom[number]]" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" style="width: 70px;" class="validate[required,custom[number]]" id="price'+index5+'" name="price'+index5+'" /></td>';
	template+='<td class="quater-input"><input type="text" class="input100px" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+='<td class="quater-input"><input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'"  id="dis-type-'+index5+'" value="2" />Fix Value &nbsp;<input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'" id="dis-type2-'+index5+'" value="1" checked="checked" />% &nbsp;<input type="text"  onChange="calculatePrice('+index5+')" class="input70px" id="dis-value'+index5+'" name="dis-value'+index5+'" /> =<input type="text" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td class="quater-input"><input type="text" class="input100px" readonly="readonly" id="after_discount'+index5+'" name="after_discount'+index5+'" /></td>';
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#orderFrm").validationEngine();
}

//add default row or record when click
$('#new_item').click(addRow);
//add default row or record when ready
jQuery(document).ready(function(){
	addRow();
});

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

	// total price
	netTotal();
	doTotal();
}
function doTotal() {
	var discountType = $('input:radio[name="discount_type"]:checked').val();
	var discountValue = ($('#discount_value').val() == '')? 0 : $('#discount_value').val();
	var netTotal = ($('#net_total').val()=='')?0 : $('#net_total').val();
	var discountReal = 0;
	discountReal = (discountType == 1)? (netTotal * discountValue) / 100 : discountValue;
	$('#discount_real').val(discountReal);
	var allTotal = Number(netTotal)-Number(discountReal);
	$('#all_total').val(allTotal);
	$('#remain').val(allTotal);
}

function netTotal() {
	// total for all record(total part)
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#after_discount'+rowIDArray[n]).val());
	}
	$('#net_total').val(netTotal);
}

function doRemain() {
	// total for all record(total part)
	var total = $('#all_total').val();
	var paid = $('#paid').val();
	var remain = total-paid;
	$('#remain').val(remain);
}
// Calculate price of order
function calculatePrice(index) {
	// total price
	var price = $('#price'+index).val();
	var qty = $('#qty'+index).val();
	var total = price * qty;
	$('#total'+index).val(total);

	// discount of total price
	var disType = $('input:radio[name=dis-type-'+index+']:checked').val();
	var disValue = ($('#dis-value'+index).val() == '')? 0 : $('#dis-value'+index).val();
	var discount = (disType == 1)? total * disValue / 100 : disValue;
	$('#real-value'+index).val(discount);
	var lastTotal = $('#total'+index).val() - discount;
	$('#after_discount'+index).val(lastTotal);
	// total price
	netTotal();
	doTotal();
}
</script>
<?php  $url_check =  $this->url(array('module'=>'purchase','controller'=>'Index','action'=>'check'));?>
<script type = "text/javascript">
			$(document).ready(function(){ //when the document is ready, run the function
				$('#feedback').load('<?php echo $url_check?>').show();
				
				$('#txt_order').keyup(function(){

					$.post('<?php echo $url_check;?>', { username: orderFrm.txt_order.value },
						function(result){
							$('#feedback').html(result).show();
						});
					
				});
			});
</script>
</script>

<?php $url_getcurrent_item =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'get-customer-info')); ?>
<script>
function getCustomerInfo(){
	var vendor_id = $("#v_name").val();
	//var location_id = $("#LocationId").val();
	$.ajax({
        url: "<?php echo $url_getcurrent_item;?>",
        type: "post",
        data: {'vendor_id':vendor_id},
        success: function(data){
            //alert(data);
            val = $.parseJSON(data);
            alert("Info has been filled");
            $("#contact").val(val.contact_name);
            $("#txt_phone").val(val.phone);
            $("#vendor_address").val(val.address);
        },
        error:function(){
            alert("Please Select Vendor");
            $("#result").html('There is error while submit');
        }
    });
}
</script>