<?php 
	$linkid=$this->getorder_id;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$url_submit =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'update-purchase-order'));
	$url_cancel =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));	
	$url_advance =  $this->url(array('module'=>'purchase','controller'=>'advance','action'=>'advance'));
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add-purchase'));
	$rowLostItems = $this->rowsOrder;
	defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
?>
<title><?php echo $tr->translate("UPDATE_PURCHASE_ORDER");?></title>
<div class="wrapper">
     <div class="clear"></div>
    <div class="right">
    	<form id="orderFrm" action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
    	<div class="contorl-cus">
        	<?php  $frmctrol=$this->control ;?>
        	<!-- <a href="<?php //echo $url_new ?>" class="new"><?php // echo $tr->translate("NEW");?></a>
        	<?php 
        		//echo $frmctrol->getElement('Update');
			    //echo $frmctrol->getElement("SaveNew");
			?>
        	<a href="<?php //echo $url_cancel ?>" class="cancel"><?php //echo $tr->translate("CANCEL");?></a> -->
    		
    		
        </div>
        <?php echo $form->getElement("id");?>
    		<?php echo $form->getElement("oldStatus");?>
			<?php echo $form->getElement("old_location");?>
        <div class="style-form" style="padding:20px 20px 5px 20px;">
		        <div class="view-table">
				   	<div class="head_form">
				   		<?php echo $tr->translate("VENDOR_INFO");?>
				   	</div>
				   	<div class="contain_form shadow">
					   	<table>
				                <tr>
				                 <?php echo $form->getElement("recieve_id");?>
				                	<td><?php echo $tr->translate("VENDOR_NAME");?>
				                	</td>
				                	<td width="34%"><?php echo $form->getElement("v_name");?>              
				                        <div id='userInfo'></div>
				                    </td>
				                    <td><?php echo $tr->translate("LOCATION_NAME");?></td>
				                    <td width="33%"><?php echo $form->getElement("LocationId");?></td>
				                </tr>
				                <tr>
				                	<td><?php  echo $tr->translate("ORDER_DATE"); //echo $tr->translate("CON_NAME");?></td>
				                    <td><?php echo $form->getElement("order_date");?>
				                       <?php //echo $form->getElement('contact'); ?>
				                    </td>          
				                    <td><?php  echo $tr->translate("INVOICE_NUM");?><div id = "feedback"></div></td>
				                    <td><?php echo $form->getElement("txt_order"); ?></td>
				                </tr>
				                 <tr>
				                	<td><?php  echo $tr->translate("DATE_IN"); //echo $tr->translate("CON_NAME");?></td>
				                    <td><?php echo $form->getElement("date_in");?></td>  
				                    <td><?php echo $tr->translate("STATUS");?></td>
				                    <td><?php echo $form->getElement("status");?></td>
				                    <td><?php echo $form->getElement("history_id");?></td>
				                    <td><?php echo $form->getElement("old_history_date");?></td>
				                    
				                </tr>
<!-- 				                <tr> 
				                	<td><?php //echo $tr->translate("CON_NUM");?></td>
				                    <td><?php //echo $form->getElement("txt_phone"); ?></td>
				                    <td><?php //echo $tr->translate("ORDER_DATE");?></td>
				                    <td><?php //echo $form->getElement("order_date");?></td>-->
				                    
<!-- 				                </tr> -->
<!-- 				                <tr> 
				                	<td><?php //echo $tr->translate("VENDOR_ADD");?></td>
				                    <td><?php //echo $form->getElement("vendor_address");?></td>
				                    <td><?php //echo $tr->translate("STATUS");?></td>
				                    <td><?php //echo $form->getElement("status");?></td>
<!-- 				                </tr> -->
				                 
				            </table>
				   	</div><!-- end of .contain_form -->
				</div><!-- end of .view-table -->
		  </div>
		   <div id="tabs" class="tabs-bottom">
					<ul style="border-top:1px solid #999;">
						<li><a href="#tabs-1"><?php echo $tr->translate("PURCAHSE_ORDER");?></a></li>
						<!-- <li><a class="tab-link" onclick="openAdvance()" href="#tabls-0"><?php echo $tr->translate("ADVANCE");?></a></li> -->
					</ul>
					<div class="tabs-spacer"></div>
					<div id="tabs-1">
					    <div class="head_form">
							<?php echo $tr->translate("PURCHASE_ORDER_LIST_CAP");?>
						</div>
						<div class="contain_form">
						   	<div class="view-table">
				        	<table class="collape" id="order_item">
										<tr height="33px">
											<td class="sub-tdheader"><?php echo $tr->translate("DEL");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
											<td class="sub-tdheader" width="100px"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("QTY_UNIT");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("QTY_PER_UNIT");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("QTY_ORDER_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
											<!-- <td class="sub-tdheader"><?php //echo $tr->translate("TOTAL_PRICE_CAP");?></td>
											<td class="sub-tdheader"><?php //echo $tr->translate("DISCOUNT_CAP");?></td> -->
											<td class="sub-tdheader"><?php echo $tr->translate("SUB_TOTAL_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("REMARK_CAP");?></td>
										</tr>
							</table>
							</div>
									<table>
										<tr>
											<td class="new-row">
												<div class="btn">
													<button class="positive" type="button" id="new_item"  name= "new_followup" value="<?php echo $tr->translate("NEW");?>">
														&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
													</button>
												</div>
												<input type="hidden" id="identity" name="identity" />
											</td>
										</tr>
									</table>
									<div class="view-table shadow">
									<table style="width:95%; margin:0 auto;" class="margin">
						                <tr class="height">
						                	<td width="2%"><?php //echo $tr->translate("PAYMENT_METHOD");?></td>
						                    <td width="40%">
						                    	<?php //echo $form->getElement("payment_name");?>
						                    </td>
						                    <td></td>
						                    <td width="40%"> </td>
						                </tr>
						                <tr class="height">
						                	<td width="2%"><?php //echo $tr->translate("PAYMENT_METHOD");?></td>
						                    <td width="40%">
						                    	<?php //echo $form->getElement("payment_name");?>
						                    </td>
						                    <td>តម្លៃសរុប​ :</td>
						                    <td width="40%"><?php echo $form->getElement("totalAmoun");?> </td>
						                </tr>
						                <tr class="height">
						                	<td><?php //echo $tr->translate("PRICE_CURRENCY");?></td>
						                    <td>
						                    	<?php //echo $form->getElement("currency");?>
						                    	<?php echo $tr->translate("REMARK");?>
						                    </td>
						                    <td><?php echo $tr->translate("PAID");?></td>
						                    <td><?php echo $form->getElement("paid");?></td>
						                </tr>
						                <tr class="height">
						                	<td></td>
						                    <td><?php echo $form->getElement("remark");?></td>
				
						                    <td><?php echo $tr->translate("BALANCE");?></td>
						                    <td><?php echo $form->getElement("remain");?></td>
						                </tr>
						                <tr>
						                	<td></td>
						                	<td></td>
						                	<td colspan="2">
						                	<?php if($this->status!=6){?>
						                        <input class="btn_submit" type="submit" name="update" value="<?php echo  $tr->translate("UPDATE");?>" />
						                        <input class="btn_submit" type="submit" name="cancel_order" value="<?php echo  $tr->translate("CAN_PO_ORDER");?>" />
						                        
						                    <?php }else{?>
						                    		<input class="btn_submit" id="update_data" type="submit" Onclick="submitData()" name="update" value="<?php echo  $tr->translate("RE_SO_ORDER");?>" />
						                    <?php }?>
						                    	<input id="btnCancel_frm" class="btn_submit" type="button" Onclick="Cancel()" value="<?php echo $tr->translate("CANCEL");?>" />
						                    </td>
						                </tr>
						                 
						            </table>	
						       </div><!-- end of .view-table -->
				        </div><!-- end of .contain_form -->

					           
						     </div><!-- tab1 -->
		            </div><!-- main tab -->			
    	</form>
    </div><!-- end right -->
</div><!-- end wrapper -->
<!-- end new product -->
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_product= $this->form_add_product;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 100%; margin:0px 15px;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("ITEM");?></td>
					<td><?php echo $frm_product->getElement("txt_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("ITEM_CODE");?></td>
					<td><?php echo $frm_product->getElement("item_code");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CATEGORY_NAME");?></td>
					<td><?php echo $frm_product->getElement("category_id");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("BRANCH_NAME");?></td>
					<td><?php echo $frm_product->getElement("brand_id");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_product->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addProduct()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="Cancel" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
 <!-- end new vendor -->
<div id="overlay-location" class="web_dialog_overlay"></div>
		<?php $form_stock = $this->form_addstock; ?>
		<div id="dialog-location" class="web_dialog">
		<form id="frm-location">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_LOCATION");?>
				<a href="#" id="btnCloseLocation" class="cancelDailog"></a>
			</div>
			<table class="frm-vendor">
				<tr>
					<td><?php echo $tr->translate("LOCATION_NAME");?></td>
					<td><?php echo $form_stock->getElement("StockName");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $form_stock->getElement("ContactName");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $form_stock->getElement("ContactNumber");?></td>
					<td><?php echo $tr->translate("STOCK_ADD");?></td>
					<td><?php echo $form_stock->getElement("location_add");?></td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $form_stock->getElement("description");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewLocation()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btncancel_location" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					<td colspan="2"></td>
				</tr>
	       </table>
	     </form>
 </div>
 <!-- add new customer -->
<div id="overlay-vendor" class="web_dialog_overlay"></div>
<?php $frm_vendor= $this->form_vendor;?>
		<div id="dialog-vendor" class="web_dialog">
		<form id="frmvendor">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_VENDOR");?>
				<a href="#" id="btnClosevendor" class="cancelDailog"></a>
			</div>
			<table class="frm-vendor">
				<tr>
					<td width="70px"><?php echo $tr->translate("VENDOR_NAME");?></td>
					<td><?php echo $frm_vendor->getElement("vendor_name");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $frm_vendor->getElement("txt_contact_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $frm_vendor->getElement("v_phone");?></td>
					<td><?php echo $tr->translate("VENDOR_ADD");?></td>
					<td rowspan="2"><?php echo $frm_vendor->getElement("txt_address");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("EMAIL");?></td>
					<td><?php echo $frm_vendor->getElement('txt_mail');?></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td colspan="2">
						<input id="btn_add" Onclick="addNewVendor()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancelVendor" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>					
				</tr>
	       </table>
	     </form>
 </div>
 
<script type="text/javascript">
jQuery(document).ready(function(){
	var index5 = '<?php echo count($rowLostItems);?>';
	var option5 = '<?php echo $this->itemsOption; ?>';
	var baseUrl = '<?php echo BASE_URL; ?>';
	var template = '';
	// add Item
	$('#new_item').click(function(){
		index5++;
		var inp = '';
		//var inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="">';
    	
		template='<tr id="row_order_'+index5+'" style="height:33px;">';
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		template+='<td class="quater-input" width="3%" align="center">'+index5+'</td>';
		template+='<td class="quater-input" width="35%"><select Onchange="showPopupProduct('+ index5 + ')" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select>'+inp+'</td>';

		template+='<td class="quater-input"><input type="text" onBlur="totalQty('+index5+')" class="validate[required,custom[number]] input" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" onBlur="totalQty('+index5+')" class="validate[required,custom[number]] input" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]] input" id="qty'+index5+'" name="qty'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]] input" id="price'+index5+'" name="price'+index5+'"/></td>';
		
		template+='<td class="quater-input"><input type="text" readonly="readonly" onBlur="calculatePrice('+index5+')" class="input" id="total'+index5+'" name="total'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" class="input" id="remark_'+index5+'" name="remark_'+index5+'" /></td>';
		//template+='<td class="quater-input"><input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'"  id="dis-type1-'+index5+'" value="2" />Fix Value &nbsp;<input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'" id="dis-type2-'+index5+'" value="1" checked="checked" />% &nbsp;<input type="text"  onChange="calculatePrice('+index5+')" class="input70px input" id="dis-value'+index5+'" name="dis-value'+index5+'" /> =<input type="text" readonly="readonly" class="input70px input" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
		//template+='<td class="quater-input"><input type="text" readonly="readonly" class="input100px input" id="after_discount'+index5+'" name="after_discount'+index5+'" /></td>';
		template+="</tr>";
		$('#order_item').append(template);
		var preIdentity = $('#identity').val();
		$('#identity').val(preIdentity+','+index5);
		$("#orderFrm").validationEngine();
		$("#item_id_"+index5).chosen();
	});

	initList();
	$('#orderFrm').validationEngine();
});

//show row of order item
function initList() {
	var template;
	var optionItem = '<?php echo $this->itemsOption;?>';
	<?php if(!empty($rowLostItems)) {
		foreach($rowLostItems AS $i=>$r){
			$inx = $i +1;?>
			template='<tr id="row_order_<?php echo $inx;?>" style="height:33px;">';
			if(<?php echo $inx;?> == 1) {
			template+='<td class="quater-input center"></td>';
			} else {
			template+='<td class="quater-input"><img onClick="deleteRecord(<?php echo $inx;?>)" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			}
			
			template+='<td class="quater-input" width="3%" align="center"><?php echo $inx;?></td>';
			template+='<td class="quater-input" width="35%"><select Onchange="showPopupProduct(<?php echo $inx;?>)" id="item_id_<?php echo $inx;?>" name="item_id_<?php echo $inx;?>" >'+optionItem+'</select></td>';
			template+='<td class="quater-input"><input type="text" onkeydown ="totalQty(<?php echo $inx;?>)" class="validate[required,custom[number]] input" name="qty_unit_<?php echo $inx;?>" id="qty_unit_<?php echo $inx;?>" /></td>';
			template+='<td class="quater-input"><input type="text" Onblur="totalQty(<?php echo $inx;?>)" class="validate[required,custom[number]] input" name="qty_per_unit_<?php echo $inx;?>" id="qty_per_unit_<?php echo $inx;?>" /></td>';

			
			template+='<td class="quater-input"><input class="input" onBlur="calculatePrice(\'<?php echo $inx;?>\')" type="text" id="qty<?php echo $inx;?>" name="qty<?php echo $inx;?>"/></td>';
			template+='<td class="quater-input"><input type="text" onBlur="calculatePrice(\'<?php echo $inx;?>\')" type="text" class="validate[required,custom[number]] input" id="price<?php echo $inx;?>" name="price<?php echo $inx;?>"/></td>';
			template+='<td class="quater-input"><input type="text" onchange="netTotal(\'<?php echo $inx;?>\')" class="input" readonly="readonly" id="total<?php echo $inx;?>" name="total<?php echo $inx;?>" /></td>';
			template+='<td class="quater-input"><input type="text" class="input" id="remark_<?php echo $inx;?>" name="remark_<?php echo $inx;?>" /></td>';
			template+='</tr>';
			$('#order_item').append(template);

			$('#item_id_<?php echo $inx;?>').val('<?php echo $r['pro_id'];?>');
			rs=<?php echo $r['qty_order'] % $r['qty_perunit']; ?>;
				
			$('#qty_unit_<?php echo $inx;?>').val('<?php echo ($r['qty_order']-($r['qty_order'] % $r['qty_perunit'])) / $r['qty_perunit']; ?>');
			$('#qty_per_unit_<?php echo $inx;?>').val('<?php echo $r['qty_order'] % $r['qty_perunit']; ?>');
		
			$('#price<?php echo $inx;?>').val('<?php echo $r['price'];?>');
			$('#qty<?php echo $inx;?>').val('<?php echo $r['qty_order'];?>');
			$('#total<?php echo $inx;?>').val('<?php echo $r['sub_total']; ?>');
			$('#remark_<?php echo $inx;?>').val('<?php echo $r['remark']; ?>');
			$('#item_id_<?php echo $inx;?>').chosen();
			if(<?php echo $inx;?>!=1) {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+<?php echo $inx;?>);
			} else {$('#identity').val(<?php echo $inx;?>);}
		<?php } }?>
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

	// total price
	netTotal();
	doTotal();
}

function totalQty(index){
	//alert(index);
// 	unit = $("#qty_unit_"+index).val();
// 	qty_per_unit = $("#qty_per_unit_"+index).val();
// 	total_qty=unit*qty_per_unit;
// 	$("#qty"+index).val(total_qty);
	//calculatePrice(index);
	getQtyById(index);
	calculatePrice(index);
	netTotal();
	
}


//Calculate price of order
function calculatePrice(index) {
	// total price
	//alert(22);
	var price = $('#price'+index).val();
	var qty = $('#qty'+index).val();

	var total = price * qty;
	$('#total'+index).val(total);

	// discount of total price
	/*var disType = $('input:radio[name=dis-type-'+index+']:checked').val();
	var disValue = ($('#dis-value'+index).val() == '')? 0 : $('#dis-value'+index).val();
	var discount = (disType == 1)? total * disValue / 100 : disValue;
	$('#real-value'+index).val(discount);
	var lastTotal = $('#total'+index).val() - discount;
	$('#after_discount'+index).val(lastTotal);*/
	// total price
// 	netTotal();
// 	doRemain();
}
function doTotal() {
	/*var discountType = $('input:radio[name="discount_type"]:checked').val();
	var discountValue = ($('#discount_value').val() == '')? 0 : $('#discount_value').val();
	var netTotal = ($('#net_total').val()=='')?0 : $('#net_total').val();
	var discountReal = 0;
	discountReal = (discountType == 1)? (netTotal * discountValue) / 100 : discountValue;
	$('#discount_real').val(discountReal);
	var allTotal = Number(netTotal)-Number(discountReal);
	$('#all_total').val(allTotal);
	$('#remain').val(allTotal);*/
}
function doRemain() {
	// total for all record(total part)
	var total = $('#totalAmoun').val();
	var paid = $('#paid').val();
	var remain = total-paid;
	//alert(remain);
	$('#remain').val(remain);
}

function netTotal() {
	// total for all record(total part)

	var netTotal=0;
	var paid = $("#paid").val();
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal);
	$('#totalAmoun').val(netTotal);
	var totalremain = netTotal - paid;
	$('#remain').val(totalremain);
}
</script>
<?php $url_getcurrentitem =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'get-customer-info')); ?>
<script>
function getCustomerInfo(){
	var vendor_id = $("#v_name").val();
	//var location_id = $("#LocationId").val();
	if(vendor_id==-1){
		  ShowVendorDialog(true);
		  e.preventDefault();
     }
	else{
		$.ajax({
	        url: "<?php echo $url_getcurrentitem;?>",
	        type: "post",
	        data: {'vendor_id':vendor_id},
	        success: function(data){
	            //alert(data);
	            val = $.parseJSON(data);
	            $("#contact").val(val.contact_name);
	            $("#txt_phone").val(val.phone);
	            $("#vendor_address").val(val.address);
	        },
	        error:function(){
	           // alert("Please Select Vendor");
	            $("#result").html('There is error while submit');
	        }
	    });
    }
}

<?php $url_add_vendor =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'add-vendor')); ?>
function addNewVendor(){
	var v_name  = $("#vendor_name").val();
	var contact = $("#txt_contact_name").val();
	var phone   = $("#v_phone").val();
	var address = $("#txt_address").val();
	var txt_mail= $("#txt_mail").val();
	validate_text('#vendor_name');
	$.ajax({
        url: "<?php echo $url_add_vendor;?>",
        type: "post",
        data: {'v_name':v_name,'contact':contact,'phone':phone,'address':address,'txt_mail':txt_mail},
        success: function(data){
            val = $.parseJSON(data);
            $('#v_name').append($("<option></option>").attr("value",val['vid']).attr("selected",true).text(v_name));  
            $("#contact").val(contact);
            $("#txt_phone").val(phone);   
            $("#vendor_address").val(address); 
             
           // $('#v_name').next().val(v_name);           
            document.getElementById("frmvendor").reset();
            HideDialogVendor();
        },
        error:function(){
            //alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
//Add location or check popup location
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		     AddNewLocation(true);
			  e.preventDefault();
	  }	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
           $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 

           //$('#LocationId').next().val(location_name);
           document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}

//for add new product**********************************************************************
var index_record=1;
function showPopupProduct(index){
	item_id = $("#item_id_"+ index).val();
	index_record= index;
	if(item_id==-1){
		 ShowDialog(true);
         e.preventDefault();
	}
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#txt_name").val();
	var pro_code = $("#item_code").val();
	var category_id = $("#category_id").val();
	var brand_id = $("#brand_id").val();
	var remark = $("#remark_order").val();
	validate_text('#txt_name');
	validate_text('#item_code');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'category_id':category_id,'brand_id':brand_id,'remark':remark},
	        success: function(data){
	            val = $.parseJSON(data);
	            $('#item_id_'+index_record).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	            $('#item_id_'+index_record).trigger("liszt:updated");
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}
$(function() {
	$( "#tabs" ).tabs();

	// fix the classes
	$( ".tabs-bottom .ui-tabs-nav, .tabs-bottom .ui-tabs-nav > *" )
		.removeClass( "ui-corner-all ui-corner-top" )
		.addClass( "ui-corner-bottom" );
	// move the nav to the bottom
	$( ".tabs-bottom .ui-tabs-nav" ).appendTo( ".tabs-bottom" );
});
function openAdvance()
{
	
	window.open("<?php //echo BASE_URL;?>/purchase/advance/advance/id/<?php echo $linkid;?>","_parent");
}
function Cancel(){
	var comfir= confirm("តើអ្នកពិតជាចង់ចាកចេញរឺ? ");
	if(comfir==true){
		window.open("<?php echo BASE_URL;?>/purchase/index/index","_parent");
	}
}
function CheckPOInvoice(){
				
				
			}

<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){
				item_id=$("#item_id_"+index).val();
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id},
						success: function(data){
							item_qty = $.parseJSON(data);
							qty_unit=$("#qty_unit_"+index).val();
							totalqty=qty_unit*item_qty['qty_perunit'];
							if(qty_per_unit==null || qty_per_unit==""){
								//$("#qty"+index).val(qty_per_unit);
							}
							else{
								qtyunit = parseInt($("#qty_per_unit_"+index).val());
								totalqty = qty_unit*item_qty['qty_perunit'] +qtyunit;
							}
							//$("#qty"+index).val(totalqty);
							$("#qty"+index).val(totalqty);
							calculatePrice(index);
							
						},
						error:function(){
						}
					});
				}

			}

</script>