<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_new = $this->url(array('module'=>'rsvacl','controller'=>'usertype','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("USER_TYPE_CAP");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("USER_TYPE_CAP");?>
				</div>
				<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
				</div>		
			</div>
			<div class="portlet-body form">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php //echo $this->form; ?>
						<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
					<div id="divPrint" style="width: 100%;">
						<style>
							.style{
								line-height: 20px;font-size: 9px !important;
								font-family: 'Khmer OS Battambang';
							}
							ul{margin: 0;padding:0;}
							table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
							th{padding: 5px;}
							.hover:hover{background: #ccc;}
						</style>	
						<table class="table2excel" border="1" &#8203;="" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("USER_TYPE");?></td>
							<td>&nbsp;<?php echo $tr->translate("TYPE_OF");?></td>
							
		                </tr>
		                <?php $num=1; 
			                
		                if(!empty($this->rs))foreach ($this->rs AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["user_type"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["parent_id"];?></td>
						   
						</tr>
						   <?php 
							
                    }?>
		                </tbody>
		           </table>
			    </div>
		   </div>
					</div>
		   </div>
		</div>
	</div>
</div>
	