<?php 
	$url_new = $this->url(array('module'=>'branch','controller'=>'index','action'=>'add',));
	$url_edit = $this->url(array('module'=>'branch','controller'=>'index','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'branch','controller'=>'index','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("LOCATION_LIST");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_BRANCH_ADVANCE_INDEX");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("LOCATION_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('branch_name');?>
								</div>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('status');?></button>
								</div>				
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
				</div>
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						
						<div class="portlet-body">
							<div class="table-toolbar">
								
							</div>
							<table class="table table-striped table-bordered table-hover" id="sample_1">
							<thead>
								<tr>
									<th><?php echo $tr->translate("NO");?></th>
									<th><?php echo $tr->translate("BRANCH_NAME");?></th>
									<th><?php echo $tr->translate("CONTACT_NAME");?></th>
									<th><?php echo $tr->translate("PHONE");?></th>
									<th><?php echo $tr->translate("EMAIL");?></th>
									<th><?php echo $tr->translate("OFFICE_PHONE");?></th>
									<th><?php echo $tr->translate("ADDRESS");?></th>
									<th><?php echo $tr->translate("STATUS");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody style="font-size: 12px;">
								<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
								<tr class="odd gradeX">
									<td><?php echo $key+1;?></td>
									<td><?php echo $row["name"]?></td>
									<td><?php echo $row["contact"]?></td>
									<td><?php echo $row["phone"]?></td>
									<td><a href="mailto:shuxer@gmail.com"><?php echo $row["email"]?> </a></td>
									<td><?php echo $row["office_tel"]?></td>
									<td class="center"><?php echo $row["address"]?></td>
									<td>
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>
									<td>
										<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><?php echo $tr->translate("EDIT");?></a> 
									</td>
								</tr>
								<?php }}?>
							</tbody>
							</table>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->
	</div>
</div>