<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('WORK_PROCESS'));
	$user_id = Application_Model_DbTable_DbGlobal::GlobalgetUserId();	
?>
<?php  $dailywork= $this->frm_dailywork;?>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("WORK_PROCESS");?>
			</div>
			<div class="caption pull-right">
				<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'workcomplete','action'=>'index')); ?>" class="btn btn-sm green  pull-right">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form id="frm" class="form-horizontal" method="post" action="<?php //echo $this->url(array('module'=>'dailywork','controller'=>'workprocess','action'=>'add')); ?>" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Work_To_DO")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("work");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("CUSTOME_NANE")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("customer_id");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("User")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("user");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Task")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("projectname");?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("DATE")?></label>
								<div class="col-md-8">
									<div class="input-icon right"><i class="fa fa-calendar"></i>
										<?php echo $dailywork->getElement("start_date");?>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("work_status");?>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("Description")?></label>
								<div class="col-md-8">
									<?php echo $dailywork->getElement("description");?>
								</div>
							</div>
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
						<a href="<?php echo $this->baseUrl();?>/dailywork/workprocess"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
					</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>



<?php $form = $this->form_customer; ?>
<div id="customerpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php //echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmcustomer" name="frmcustomer" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Branch Name");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cu_code'); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_phone'); ?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CON_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_contact_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CON_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i><?php echo $form->getElement('contact_phone'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_TYPE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('customer_type'); ?>
									</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Customer Level");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_level'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ADDRESS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("txt_address");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("EMAIL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_mail'); ?>
								</div>
							</div>
					</div>
					
					<div class="form-group">
						<label class="control-label col-md-2"><?php echo $tr->translate("CREDIT_LIMIT");?> <span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('credit_limit'); ?>
								</div>
						</div>
						<label class="control-label col-md-2">
							<?php echo $tr->translate("CREDIT_TEARM");?><span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("credit_tearm");?>
								</div>
						</div>
						
					</div>
					
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" onclick="addNewCustomer();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CUSTOMER")?> </button>
						</label>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>
 <script>
 jQuery(document).ready(function(){
	 //alert(<?php echo $user_id;?>);
	$('#user').attr("value",<?php echo $user_id;?>).attr("selected",true);                       
    $("#user").select2();
});
 function getCustomerInfo(){
	customer_id = $("#customer_id").val();
	if(customer_id==-1){
		$('#customerpopup').modal('show');
	}
}
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	var customer_name  = $("#txt_name").val();
	$.ajax({
        url: "<?php echo $url_add_customer;?>",
        type: "post",
        data: $('#frmcustomer').serialize(),
        success: function(data){
            rs = $.parseJSON(data);
             $('#customer_id').append($("<option></option>").attr("value",rs['cus_id']).attr("selected",true).text(customer_name));                       
             $("#customer_id").select2();
			$('#customerpopup').modal('hide');
        },
        error:function(err){
            alert("faile insert");
           
        }
    });
}
function viewCustomer(){
	id = $("#customer_id").val();
	
	if(id!=-1 && id!='' && id!=0){
		window.open('<?php echo $this->url(array('module'=>'sales','controller'=>'customer','action'=>'edit')); ?>'+'/id/'+id, '_blank');
	}
}
<?php $url_getwork =  $this->url(array('module'=>'dailywork','controller'=>'workprocess','action'=>'getworkdetail')); ?>
function getWorkDetail(){
	var work_id= $("#work").val();
	$.ajax({
        url: "<?php echo $url_getwork;?>",
        type: "post",
        data: {'work_id':work_id},
        success: function(data){
            rs = $.parseJSON(data);
          
            $("#customer_id").val(rs.customer_id);
            $("#user").val(rs.user);
            $("#projectname").val(rs.projectname);
           
        },
        error:function(response, ioArgs){
        	//alert("Failed while doing the operation: " + ioArgs.xhr.response);  
        }
    });
}
</script>	