<?php
$row_rs = $this->row_rs;
?>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage(); ?>
<?php $formFilter =  $this->frm_search;?>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DAILY_WORKPROCESS");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $this->url(array('module'=>'dailywork','controller'=>'workcomplete','action'=>'add')); ?>" class="btn btn-sm green  pull-right">
						<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
			   <form method="post" action="">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><input class="form-control" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" type="text" ></label>
						<label class="control-label col-md-2"> 
							<?php echo $formFilter->getElement("user");?>
						</label>
						<label class="control-label col-md-2">
							<?php echo $formFilter->getElement("projectname");?>
						</label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><input class="form-control form-control-inline date-picker" id="start_date" name="start_date" value="<?php echo date("m/d/Y",strtotime($this->row['start_date']));?>" type="text" ></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><input class="form-control form-control-inline date-picker" id="end_date" name="end_date" value="<?php echo date("m/d/Y",strtotime($this->row['end_date']));?>" type="text" ></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>		
				</form> 
				<div class="contain_form" style="clear:both;">
					<?php echo $this->list; ?>
				</div>
		   </div>
		</div>
	</div>
</div>