<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'measure','action'=>'add',));
	$url_cancel = $this->url(array('module'=>'product','controller'=>'measure','action'=>'index',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'measure','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("ADD_MEASURE");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ADD_MEASURE");?>
			</div>
			<div class="tools">
				<label><a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a></label>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="<?php echo $url_new;?>" >
				<div class="form-body ">
					<div style="margin: 0 auto;" >
							
							<div class="form-group">
								<label class="col-md-4 control-label"><?php echo $tr->translate("MEASURE_NAME");?></label>
								<div class="col-md-6">
									<?php echo $formFilter->getElement('measure_name');?>
								</div>
												
							</div>
							<div class="form-group">
												
								<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-6">
									<?php echo $formFilter->getElement('status');?>
								</div>
							</div>
							<div class="form-group">
												
								<label class="col-md-4 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-6">
									<?php echo $formFilter->getElement('remark');?>
								</div>
							</div>
						<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<a href="<?php echo $this->baseUrl();?>/product/measure/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
									<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
									<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									
								</label>
							</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>