<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("MAKE_INVOCIE");?></title>
<div class="row">
<marquee style="margin-top:-20px;" behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5">យើងត្រូវការ ការយល់ព្រមពី ផ្នែកគណនេយ្យ /ហិរញ្ញវត្ថុ ឫអ្នកដែលមានសិទ្ធ ដើម្បី <span style="color:red;">បង្កើតជាវិក័យបត្រ និង របាយការណ៏ប្រគល់ទំនិញ</span> / We need approval from  or person who have permission to <span style="color:red;">issue invoice and Delivery Report</span> ! </marquee>
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("INVOICE_APPROVED");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'approved'));?>
	<form id="form_sample_2" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
		                <tr>
		                <td width="20%" valign="top">
		                <td width="60%" valign="top" style="text-align:left; font-size:26px; font-family:'Khmer MEF2';padding-bottom:10px;">
		                	<ul>
		                			<li style="font-size:22px; font-family:'Khmer MEF2'"><?php echo $this->product[0]['branch_code'];?></li>
		                		</ul>
		                </td>
		                <td width="20%"></td>
		                </tr> 
		                
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
		                				<td style="font-size: 12px;" valign="top" width="35%;">
		                				<div style="width:100%;display: block;font-size:16px; font-family:'Khmer MEF2';white-space: nowrap;"><u>ពត៌មានអតិថិជន / CUSTOMER INFORMATION</u></div>
		                				    <ul class='pur_info'>
			                					<li style="text-align: left;"><strong>Customer Name : </strong><?php echo $this->product[0]['customer_name'];?></li>
			                					<li style="text-align: left;"><strong>Contact Person : </strong><?php echo $this->product[0]['contact_name'];?></li>
			                					<li style="text-align: left;"><strong>Contact Number : </strong><?php echo $this->product[0]['phone'];?></li>
			                					<li style="text-align: left;"><strong>E-mail: </strong><?php echo $this->product[0]['email'];?></li>
			                					<li style="text-align: left;"><strong>Address : </strong><?php echo $this->product[0]['add_name'];?></li>
		                					</ul>
		                				</td>
		                				<td width="30%"></td>
		                				<td width="35%" style="text-align: left;font-size: 12px;" valign="top">
		                					<div style="width:100%;display: block;font-size:16px; font-family:'Khmer MEF2';"><u>វិក័យបត្រ / OFFICIAL INVOICE</u></div>
		                					<ul class='pur_info'>
			                					<li style="text-align: left;"><strong>Branch Name : </strong><?php echo $this->product[0]['branch_name'];?></li>
			                					<li style="text-align: left;"><strong>Invoice No.: </strong><?php echo $this->product[0]['sale_no'];?></li>
			                					<li style="text-align: left;"><strong>Sale No.: </strong><?php echo $this->product[0]['sale_no'];?></li>
			                					<li style="text-align: left;"><strong>Date : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['date_sold']));?></li>
		                						<li style="text-align: left;"><strong>Sale Person : </strong><?php echo $this->product[0]['staff_name'];?></li>
		                					</ul>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table  style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
		                 <tr align="center" style="font-weight:bold; line-height: 20px;  padding:1px 0px; white-space: nowrap;border:1px solid #fff;border-bottom: 1px solid #000 !important; ">
		                    <td colspan="10" align="center" style="font-size: 13px;">ទំនិញដែលបានទិញហើយក្រុមហ៊ុនយើងខ្ញុំ មិនទទួលដូរយកវិញទេ ។សូមអរគុណ
		                    <br />Goods Sold Can Not Be Returned, Thank you !</td>
		                </tr>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></td>
							<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
							<td>&nbsp;<?php echo $tr->translate("MODEL");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("SERIAL_NUM");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("OLD_PRICE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("Unit Price");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
							<td><?php echo $tr->translate("AMOUNT");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["model_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["serial_number"];?></td>
						    <?php 
						   $sing="";
						   if($rs['qty_unit']>0 AND $rs['qty_detail']>0){
						   	$sing=" + ";
						   }
						   $unitqty = floatval($rs['qty_unit']);
						   $qty_detail = floatval($rs['qty_detail']);
						   if($rs['qty_unit']>0){$unitqty=number_format($unitqty,0)." ".$rs["measue_name"];}else{$unitqty="";}
						   if($rs['qty_detail']>0){
						   	$qty_detail=number_format($qty_detail,0)." ".$rs["unit_label"];}else{$qty_detail="";}
						   ?>
						   <td style="white-space: nowrap; text-align:center;">&nbsp;<?php echo $unitqty.$sing.$qty_detail; //$rs["qty_order"];?></td>
						   <td <?php if($rs["price"]!=$rs["old_price"]){echo"style='background:red;'";}?>>&nbsp;<?php echo number_format($rs["old_price"],2);?></td>
						   <td>&nbsp;<?php echo number_format($rs["price"],2);?></td>
						   <td>&nbsp;<?php echo number_format($rs["disc_value"],2);echo ($rs["disc_type"]==1)?'%':'';?></td>
						   <td>&nbsp;<?php echo $rs["curr_name"]."&nbsp;".number_format($rs["sub_total"],2);?></td>
						</tr>
						   <?php 
                    }?>
                    <tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("TOTAL");?><input type="hidden" name="soid" id="soid" value="<?php echo ($this->product[0]['id']);?>"/><input type="hidden" name="quote_id" id="quote_id" value="<?php echo ($this->product[0]['quote_id']);?>"/></td>
						<td >&nbsp;&nbsp;<input type="hidden" name="all_total" id="all_total" value="<?php echo $this->product[0]['all_total'];?>"   ><?php echo number_format($this->product[0]['all_total'],2);?></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
						<td >&nbsp;&nbsp;
						<input type="hidden" name="discount_type" id="discount_type" value="<?php echo $this->product[0]['discount_type'];?>"   >
						<input type="hidden" name="discount" id="discount" value="<?php echo $this->product[0]['discount_value'];?>"   ><?php echo number_format($this->product[0]['discount_value'],2);echo ($this->product[0]['discount_type']==1)?'%':0;?></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?></td>
						<td >&nbsp;&nbsp;<input type="hidden" name="net_total" id="net_total" value="<?php echo $this->product[0]['net_total'];?>"   ><?php echo number_format($this->product[0]['net_total'],2);?></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("Deposit");?>​</td>
						<td ><input type="text" name="deposit" id="deposit" value="0" required="1"  style="text-align:left;border:1px solid red;" onkeyup="calculateBalance();" class="form-control"></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("BALANCE");?>​</td>
						<td ><input type="text" name="balance" id="balance" value="0" required="1"  style="text-align:left;border:1px solid red;" onkeyup="calculateBalance();" class="form-control"></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #fff;">
						<strong  style="font-size: 13px;"><u>ខសន្យា និងលក្ខណ៏ទូទៅ / General Term & Conditions</u></strong>
							<style>
								ul.termcodition li{ line-height: 20px;list-style-type: none; font-size: 12px;}
							</style>
							<ul class="termcodition">
							<?php if(!empty($this->rscondition))foreach ($this->rscondition as $key =>$rst){ ?>
								<li style="text-align: left;"><?php echo $key+1;echo "-".$rst['con_khmer'];?></li>
								<li style="text-align: left;"><?php echo $rst['con_english'];?></li>
							<?php }?>
							</ul>
						</td>
					</tr>
		            </tbody>
		           </table>
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		 <table align="center" width="100%" >
							   <tbody>
							   <tr style="font-size: 11px;">
							        <td style="text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap; width:40%;">
							        	<strong style="text-align: center;"><?php echo $tr->translate("DELIVERY_INFORMATION");?></strong>
							        </td>
							        <td></td>
							        <td style="width:40%;font-family:'Khmer MEF2';white-space: nowrap;">
							        <select name="approved_name" id="approved_name" class="form-control select2me">
							        	<option value="1">Approved</option>
							        	<option value="2">Not Approved</option>
							        </select><input type="hidden" name="id" id="id" value="<?php echo $this->product[0]['id'];?>" />
									<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->product[0]['branch_id'];?>" />
									
							        </td>
							   </tr>
							   <tr style="font-size: 11px; height: 75px;">
							        <td valign="bottom" style="text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;"><span  class="form-control" style="border: 2px dotted #ddd; height: 100px;width:100%;"><textarea name="notefrom_accountingk" id="notefrom_accountingk" style="width:100%;height:100%;" ></textarea></span></td>
							        <td></td>
							        <td valign="bottom" style="text-align:center; font-family:'Khmer MEF2';white-space: nowrap;"><textarea name="app_remark" id="app_remark" class="form-control" rows="3" cols="80" placeHolder="Approval Comment Here"></textarea></td>
							   </tr>
							   <tr style="font-size: 11px;">
							        <td style="text-align:center;white-space: nowrap;"><strong>ថ្ងៃត្រូវដឹកជញ្ចួន /Delivery Date</strong><div class="input-icon right"><i class="fa fa-calendar"></i><input name="dilivery_date" id="dilivery_date" value="<?php echo date("m/d/Y");?>" class="form-control form-control-inline date-picker" /></div></td>
							        <td></td>
							        <td style="text-align:center;white-space: nowrap;"><strong>ថ្ងៃខែយល់ព្រម /Approved Date</strong><div class="input-icon right"><i class="fa fa-calendar"></i><input name="app_date" id="app_date" value="<?php echo date("m/d/Y");?>" class="form-control form-control-inline date-picker" /></div></td>
							   </tr>
							  
							</tbody>
						</table>
		
		<div class="form-group">
				<label class="col-md-4 control-label"><a href="<?php echo $this->baseUrl();?>/sales/invoiceapprove/" ><button style="width:90%;" type="button" class="btn blue btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a></label>
				<div class="col-md-4 control-label"><button type="submit" name="print" value="print" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_MAKEINVOICE")?></button></div>
		        <div class="col-md-4 control-label"><button type="submit" name="saveprint" value="saveprint" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRINTINVOICE")?></button></div>
		</div>
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 

 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = parseFloat(net_total)-parseFloat(deposit);
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
