
<?php 
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_new =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'));
$url_submit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add'));
$url_edit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'));
$form=$this->form;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("ADD_NEW_CUSTOMER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
				</div>
				<div class="caption" style="float:right">
					<a href="<?php echo $url_new;?>" class="btn btn-bg blue  ">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Branch Name");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CU_CODE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cu_code'); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_phone'); ?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CON_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_contact_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CON_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i><?php echo $form->getElement('contact_phone'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ZONE_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('zone_name'); ?>
									</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Customer Level");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_level'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ADDRESS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("txt_address");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Province");?><span class="required">
								</span>
								<div><?php //echo $tr->translate("DISTRICT");?><span class="required">
								</span></div>
							</label>
							<label class="col-md-4">
									<i class="fa"></i>
									<?php echo $form->getElement('province'); ?>
									<div class="col-md-6">
									<?php //echo $form->getElement('district'); ?>
									</div>
									<div class="col-md-6">
									<?php //echo $form->getElement('commune'); ?>
									</div>
							</label>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("COMMUNE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php //echo $form->getElement('commune'); ?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("EMAIL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									
									<?php echo $form->getElement('txt_mail'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("FAX");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_fax'); ?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("WEBSITE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_website'); ?>
								</div>
							</div>
					</div>
					<?php 
						$session_user=new Zend_Session_Namespace('auth');
						$level=$session_user->level;
						$str_display="hidden";
						if($level==1){ 
							$str_display="visible";
						}
					?>
					<div class="form-group">
						<div style="visibility:<?php echo $str_display;?>" >
							<label class="control-label col-md-2"><?php echo $tr->translate("CREDIT_LIMIT");?> <span class="required">
									</span>
							</label>
							<div class="col-md-2">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('credit_limit'); ?>
									</div>
							</div>
							<label class="control-label col-md-1">
								<?php echo $tr->translate("CREDIT_TEARM");?><span class="required">
									</span>
							</label>
							<div class="col-md-1">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement("credit_tearm");?>
									</div>
							</div>
							<label class="control-label col-md-2">
								<?php echo $tr->translate("REMARK");?><span class="required">
									</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement("remark");?>
									</div>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<div class="form-group">
							<div class="col-md-3"></div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/sales/customer"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" name="saveclose" value="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-2">
								<button type="submit" name="btnsavenew"  name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							<div class="col-md-3"></div>
						</div>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
</body>
</html>
 <script>
$('#frm').submit(function() {
		zone_name = $("#zone_name").val();
	    if(zone_name==''){
	        alert("Please Select Zone Name!!!");
	        $('#zone_name').select2('open');
	        return false;
	    }
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
		    return true;
		} else {
		   return false;
		}
});
	
 $(document).ready(function() {
	getCustomerLimit();
});
 <?php $url_customer_limit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'getcustomerlimit')); ?>
function getCustomerLimit(){
				id=$("#customer_type").val();
				$.ajax({
						url:"<?php echo $url_customer_limit;?>",
						type:"post",
						data:{'id':id},
						success: function(data){
							value = $.parseJSON(data);
							if(value!=""){
								$('#credit_limit').val(value.credit_limit);
								$("#credit_tearm").val(value.credit_term);
							}
						},
						error:function(e){
							//alert(e);
						}
					});
}
$('#frm').submit(function() {
//aa = $("#frm").validationEngine();
//alert(JSON.stringify(aa));
//return false;
	customer_id=$("#customer_type").val();
	if(customer_id=='' || customer_id==-1){
		alert("Please select customer type");
		$('#customer_type').select2('open');
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("Please add product row");
		$('#add_item').select2('open');
		return false;
	}
});
</script>
<script>
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-cu-code')); ?>
function getCustomerCode(){
				id=$("#branch_id").val();
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'id':id},
						success: function(data){
							value = $.parseJSON(data);
								$("#cu_code").val(value);
						},
						error:function(e){
							alert(e);
						}
					});
}
<?php $url_getdistrict=  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'getdistrict')); ?>
function getDistrict(){
	distict_id = $("#district").val();
	$.ajax({
		url:"<?php echo $url_getdistrict;?>",
		type:"post",
		data:{'distict_id':distict_id},
		success: function(data){
			value = $.parseJSON(data);
				$("#cu_code").val(value);
		},
		error:function(e){
			//alert(e);
		}
	});
}
<?php $url_getcommune=  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'getcommune')); ?>
function getCommune(){
	distict_id = $("#district").val();
	$.ajax({
		url:"<?php echo $url_code;?>",
		type:"post",
		data:{'id':id},
		success: function(data){
			value = $.parseJSON(data);
				$("#cu_code").val(value);
		},
		error:function(e){
			alert(e);
		}
	});
}

function getPopupZone(){
	val = $('#zone_name').val();
	if(val==-1){
		$('#zone_popup').modal('show');
	}
}

<?php $url_add_zone=  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-new-zone')); ?>
function addNewZone(){
	var cat_name  = $("#title_en").val();
	$.ajax({
		url: "<?php echo $url_add_zone;?>",
		type: "post",
		data: $('#frm_zone').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			 $('#zone_name').append($("<option></option>").attr("value",rs['cat_id']).attr("selected",true).text(cat_name));                       
			 $("#zone_name").select2();
			 $("#frm_zone").trigger('reset');
			 $('#zone_popup').modal('hide');
		},
		error:function(err){
			alert("faile insert");
		   
		}
	});
}

</script>


<!-- Zone  Popup -->
<?php $frm = $this->Form; ?>
<div id="zone_popup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PRODUCT_CATEGORY");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frm_zone" name="frm_zone" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
					 		<div class="form-group">
					 		    
								<label class="col-md-3 control-label"><?php echo $tr->translate("TITLE");?></label>
								<div class="col-md-8">
									<?php echo $frm->getElement('title_en');?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-3 control-label"><?php echo $tr->translate("ADDRESS");?></label>
								<div class="col-md-8">
									<?php echo $frm->getElement('txt_address');?>
								</div>
							</div>
							<div class="form-group">
								 				
								<label class="col-md-3 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-8">
									<?php echo $frm->getElement('status');?>
								</div>
								 
							</div>
							<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<button type="button" name="btnsavenew" onclick="addNewZone();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?> </button>
								</label>
							</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
          </div>
        </div>
    </div>
 </div>	