
<?php 
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_new =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'));
$url_submit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add'));
$url_edit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'));
$form=$this->form;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$user_info = new Application_Model_DbTable_DbGetUserInfo();
$result = $user_info->getUserInfo();
$level = $result["level"];
?>
<title><?php echo $tr->translate("ADD_NEW_CUSTOMER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" class="btn btn-sm green  ">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="form_sample_2" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("Branch Name");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CU_CODE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cu_code'); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("COMPANY_NUMBER");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_phone'); ?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CON_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_contact_name'); ?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CON_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i><?php echo $form->getElement('contact_phone'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_TYPE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('customer_type'); ?>
									</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Customer Level");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_level'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("VENDOR_ADD");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("txt_address");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("Province");?><span class="required">
								</span>
								<div><?php echo $tr->translate("EMAIL");?><span class="required">
								</span></div>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('province'); ?>
									<?php echo $form->getElement('txt_mail'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("FAX");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_fax'); ?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("WEBSITE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('txt_website'); ?>
								</div>
							</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-2"><?php echo $tr->translate("CREDIT_LIMIT");?> <span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('credit_limit'); ?>
								</div>
						</div>
						<label class="control-label col-md-2">
							<?php echo $tr->translate("CREDIT_TEARM");?><span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("credit_tearm");?>
								</div>
						</div>
						
					</div>
					<div class="form-group">
						
						<div class="col-md-6">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php //echo $form->getElement("credit_tearm");?>
								</div>
						</div>
						
						<label class="control-label col-md-2">
							<?php echo $tr->translate("REMARK");?><span class="required">
								</span>
						</label>
						<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("remark");?>
								</div>
						</div>
					</div>
					<div class="form-group">
							<div class="col-md-4">
								<a href="<?php echo $this->baseUrl();?>/sales/customer"><button type="button" class="btn blue btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-4">
								<div class="input-icon right">
									<button type="submit" name="saveclose" value="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-4">
								<button type="submit" name="btnsavenew"  name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
</body>
</html>
<script>
$(document).ready(function() {
	user_level = <?php echo $level;?>;
	//alert(1);
	if(user_level!=1 && user_level!=2){
		$('#credit_limit').attr('readOnly',true);
		$("#credit_tearm").attr('readOnly',true);
	}
});
<?php $url_customer_limit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'getcustomerlimit')); ?>
function getCustomerLimit(){
				id=$("#customer_type").val();
				$.ajax({
						url:"<?php echo $url_customer_limit;?>",
						type:"post",
						data:{'id':id},
						success: function(data){
							value = $.parseJSON(data);
							//alert(value);
							if(value!=""){
								$('#credit_limit').val(value.credit_limit);
								$("#credit_tearm").val(value.credit_term);
							}
						},
						error:function(e){
							//alert(e);
						}
					});
}
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-cu-code')); ?>
function getCustomerCode(){
				id=$("#branch_id").val();
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'id':id},
						success: function(data){
							value = $.parseJSON(data);
								$("#cu_code").val(value);
						},
						error:function(e){
							alert(e);
						}
					});
}
</script>