<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'addcustomertype',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->Form;
?>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("SALEORDER_LIST");?>
				</div>
				<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			    </div>
			</div>
			<div class="portlet-body form">
				<form method="post" action="">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('adv_search');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status_search');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php echo $this->list; ?>
					</div>
		   </div>
		</div>
	</div>
</div>
