<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form;
?>
<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'edit',));
	$url_cencel = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'customertypelist',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title> <?php echo $tr->translate("EDIT_ZONE")?></title>
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
						<i class="fa fa-globe"></i><?php echo $tr->translate("EDIT_ZONE");?>
				</div>
				<div class="tools">
					<a href="<?php echo $url_cencel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
				</div>
			</div>
			<div class="portlet-body form">
				<form class="form-horizontal" method="post" action="" >
					<div class="form-body ">
						<div style="margin: 0 auto;" >
								<div class="form-group">
								    <label class="col-md-3 control-label"></label>	
									<label class="col-md-2 control-label"><?php echo $tr->translate("TITLE");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('title_en');?>
									</div>
									<label class="col-md-3 control-label"></label>	
								</div>
								<div class="form-group">
								   <label class="col-md-3 control-label"></label>
									<label class="col-md-2 control-label"><?php echo $tr->translate("ADDRESS");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('txt_address');?>
									</div>
									<label class="col-md-3 control-label"></label>	
								</div>
								<div class="form-group">
									<label class="col-md-3 control-label"></label>				
									<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('status');?>
									</div>
									 <label class="col-md-3 control-label"></label>	
								</div>
								
							<div class="form-group">
	                           <label  class="col-md-12 col-md-offset-4 col-md-8">
									<a href="<?php echo $this->baseUrl();?>/sales/customer/customertypelist"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
	                                <button type="submit" name="save_close" class="btn btn-primary"><?php echo $tr->translate("SAVE_CLOSE");?></button>
	                            </label>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

