<?php
	$cancel_url=$this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user',
	    'action'=>'index',
	),null,true);
	$form=$this->form;
	Application_Model_Decorator::removeAllDecorator($form); 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_cancel = $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'));
?>
<title><?php echo $tr->translate("CHANGE_PASSWORD");?></title>
<script>
		jQuery(document).ready(function(){
		    // binds form submission and fields to the validation engine
		jQuery("#frm").validationEngine('attach', {promptPosition : "centerRight"});
		    
		});
		function validatePassword(field)
        {
            	var com=$('#confirm_password').val();
            	var pwd=$('#password').val();
        		if(com!=pwd) return '*Password mismatch!';
        }
</script>
<?php echo $this->msg; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate('CHANGE_PSW');?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3"><?php echo $tr->translate('OLD_PASSWORD');?><span class="required">
								</span>
							</label>
							<div class="col-md-6">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('current_password');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3"><?php echo $tr->translate('NEW_PASSWORD');?><span class="required">
								</span>
							</label>
							<div class="col-md-6">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('password');?>
									
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3"><?php echo $tr->translate('RE_PASSWORD');?><span class="required">
								</span>
							</label>
							<div class="col-md-6">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('confirm_password');?>
								</div>
							</div>
						</div>
						 <div class="form-group">
								<div class="col-md-4">
									<div class="input-icon right">
									</div>
								</div>
								<div class="col-md-4">
									<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								</div>
								<div class="col-md-4">
								</div>
							</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>