<?php 					
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DDELIVERY_LIST");?>
				</div>
				
			</div>
			<div class="portlet-body form">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('customer_id');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<?php //echo $this->list; ?>
						
						<div class="portlet-body">
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("LOCATION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("Com.Name");?></th>
								<th class="tdheader"><?php echo  $tr->translate("CON_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("SALE_AGENT");?></th>
								<th class="tdheader"><?php echo  $tr->translate("INVOICE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("SALE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DATE_ORDER");?></th>
								<!--<th class="tdheader"><?php echo  $tr->translate("CURRNECY_TYPE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TOTAL");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DISCOUNT");?></th>-->
								<th class="tdheader"><?php echo  $tr->translate("TOTAL_AMOUNT");?></th>
								<th class="tdheader"><?php echo  $tr->translate("APPROVED_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PENDING_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){ foreach ($this->rs as $key => $row){
									$edit_status = '';
									if($row["appr_pedding"]>1){
										$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
									}
									$add = '';
									$cancel="style='pointer-events: none;cursor: default;color: #ccc;'";
									if($row["is_todeliver"]==1){
										$cancel = '';
										$add="style='pointer-events: none;cursor: default;color: #ccc;'";
									}
							?>
								
								<tr class="odd gradeX">
									<td class="center"><?php echo $key+1;?></td>
									<td><?php echo $row["branch_name"]?></td>
									<td><?php echo $row["customer_name"]?></td>
									<td><?php echo $row["contact_name"]?></td>
									<td><?php echo $row["staff_name"]?></td>
									<td><?php echo $row["invoice_no"]?></td>
									<td><?php echo $row["sale_no"]?></td>
									<td><?php echo $row["date_sold"]?></td>
									<!--<td><?php echo $row["curr_name"]?></td>
									<td><?php echo $row["all_total"]?></td>
									<td><?php echo $row["discount_value"]?></td>-->
									<td><?php echo $row["net_total"]?></td>
									<td><?php echo $row["appr_status"]?></td>
									<td><?php echo $row["appr_pedding"]?></td>
									<td><?php echo $row["user_name"]?></td>
									
									<td style="white-space: nowrap;">
										<a <?php echo $add;?> href="<?php echo $this->baseUrl();?>/sales/delivery/add/id/<?php echo $row["id"]?>"><?php echo $tr->translate("DELIVER");?></a> | 
										<a <?php echo $cancel;?> href="<?php echo $this->baseUrl();?>/sales/delivery/cancel/id/<?php echo $row["id"]?>"><?php echo $tr->translate("CANCEL_DELIVER");?></a>
									</td>
								</tr>
								<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table>
				</div>
			<?php echo $footer?>
					</div>
		   </div>
		</div>
	</div>
</div>