<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs)."sfsgesd";
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?>
				</div>
				<!--<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>-->
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('purchase_status');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>			
				</form> 
				<div class="contain_form" style="clear: both;">
					<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("LOCATION_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PURCHAE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("INVOICE_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ORDER_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("VENDOR");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PROCESSING");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									$receive = 0;
									if($rs["purchase_status"]==5){
										$receive = 1;
									}
									
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["branch"];?></td>
									<td class="items"><?php echo $rs["order_number"];?></td>
									<td class="items"><?php echo $rs["invoice_no"];?></td>
									<td class="items"><?php echo $rs["date_order"];?></td>
									<td class="items"><?php echo $rs["vendor"];?></td>
									<td class="items"><?php echo $rs["p_status"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<?php if($receive==1){ ?>
											<a target="_blank" href="<?php echo $this->baseUrl();?>/purchase/receive/receivenote/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT_RECEIVE_ORDER");?></a>
										<?php }else{?>
											<a href="<?php echo $this->baseUrl();?>/purchase/receive/add/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("RECEIVE_PURCHASE");?></a>
										<?php }?>
										
									</td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>