<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'receive','action'=>'add-recieve',));
	$url_delete = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'delete-purchase-order',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$mylevel = $this->level;
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<div class="right" style="padding:10px; width: 97%">
<div class="wrapper">
  <div style="width:98%; margin:0 auto;">
		<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="view-table shadow margin">
							<table style="width: 100%;">
								<tr class="height">
									<td><?php echo $tr->translate("INVOICE_NUM");?></td>
									<td width="30%"><?php echo $formFilter->getElement('order');?></td>
									<td><?php echo $tr->translate("VENDOR_NAME");?></td>												
									<td width="30%"><?php echo $formFilter->getElement('vendor_name');?></td>	
								</tr>
<!-- 								<tr class="height"> -->
									<!--  <td><?php //echo $tr->translate("STATUS");?></td>-->
									<!--<td width="30%"><?php //echo $formFilter->getElement('status');?></td>-->
									<!--<td><?php //echo $tr->translate("VENDOR_NAME");?></td>												
									<!--<td width="30%"><?php //echo $formFilter->getElement('vendor_name');?></td>	-->
<!-- 								</tr> -->
								<tr class="height">
									<td><?php echo $tr->translate("START_DATE");?></td>
									<td><?php echo $formFilter->getElement('search_start_date');?></td>
									<td><?php echo $tr->translate("END_DATE");?></td>
									<td><?php echo $formFilter->getElement('search_end_date');?></td>
								</tr>
								<tr class="height">
									<td colspan="2" class="btn"></td>
									<td class="btn"></td>
									<td class="btn"><input type="submit" value="<?php echo $tr->translate("REFRESH");?>" /></td>
								</tr>
								<tr class="height">
									<td colspan="2" class="btn"></td>
									<td class="btn"></td>
									<td class="btn" colspan="2">
										<div class="btn" align="right">
											<?php 
											if($mylevel==1 OR $mylevel==2){
												$formList = new Application_Form_Frmlist();
												echo $formList->showAddBuntton($url_new);
												//echo $formList->showDeleteBuntton($url_delete);
											}
											?>
										</div>
									</td>
								</tr>
							</table>
					     </div>
							<br/>
				  	<div class="">
						<div class="head_form">
							<?php echo $tr->translate("PURCHASE_ORDER_LIST_CAP");?>
						</div>
						<div class="contain_form">
							<?php echo $this->list; ?>
						</div>
					</div>
				</form> 
	</div>
</div><!-- end wrapper -->
</div><!-- end of .right -->