<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>Purchase Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PURCHASE_REPORT");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'">របាយការណ៏ បញ្ជាទិញ</li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 12px;" valign="top">
		                				<div style="width:100%;display: block;margin-top: 14px;font-size: 14px;font-weight: bold;">&nbsp;&nbsp;Suppliyer Info</div>
		                				   <ul class='pur_info'>
			                					<li style="text-align: left;"><strong>ឈ្មោះអ្នកផ្គត់ផ្គង់ / Suppliyer Name : </strong><?php echo $this->product[0]['vendor_name'];?></li>
			                					<li style="text-align: left;"><strong>ឈ្មោះអ្នកទំនាក់ទំនង / Contact Name : </strong><?php echo $this->product[0]['contact_name'];?></li>
			                					<li style="text-align: left;"><strong>លេខទូរសព្ទ  / Contact Number : </strong><?php echo $this->product[0]['v_phone'];?></li>
			                					<li style="text-align: left;"><strong>អាសយដ្ឋាន / Address : </strong><?php echo $this->product[0]['add_name'];?></li>
		                					</ul>
		                				</td>
		                				<td width="40%"></td>
		                				<td width="30%" style="text-align: left;font-size: 12px;">
		                					<div style="width:100%;display: block;margin-top: 14px;font-size: 14px;font-weight: bold;">&nbsp;&nbsp;Purchase Info</div>
		                					<ul class='pur_info'>
			                					<li style="text-align: left;"><strong>សាខា​ / Location: </strong><?php echo $this->product[0]['branch_name'];?></li>
			                					<li style="text-align: left;"><strong>លេខបញ្ជាទិញ / Purchase Number : </strong><?php echo $this->product[0]['order_number'];?></li>
			                					<li style="text-align: left;"><strong>លេខវិក័យបត្រ / Invoice No. : </strong><?php echo $this->product[0]['order_number'];?></li>
			                					<li style="text-align: left;"><strong>ថ្ងៃបញ្ជាទិញ / Order Date : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['date_order']));?></li>
			                					<li style="text-align: left;"><strong>ថ្ងៃទំនិញចូល / Date In : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['date_in']));?></li>
		                						<li style="text-align: left;"><strong>ស្ថានការណ៏ / Purcase Status : </strong><?php echo $this->product[0]['purchase_status'];?></li>
		                					</ul>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel"><br />
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("Products/Particulars Description");?></td>
							<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
							<td><?php echo $tr->translate("TOTAL");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
		                 <?php 
						   $sing="";
						   if($rs['qty_unit']>0 AND $rs['qty_detail']>0){
						   	$sing=" + ";
						   }
						   $unitqty = floatval($rs['qty_unit']);
						   $qty_detail = floatval($rs['qty_detail']);
						   if($rs['qty_unit']>0){$unitqty=number_format($unitqty,0)." ".$rs["measue_name"];}else{$unitqty="";}
						   if($rs['qty_detail']>0){
						   	$qty_detail=number_format($qty_detail,0)." ".$rs["unit_label"];}else{$qty_detail="";}
						 ?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap; text-align:center;">&nbsp;<?php echo $unitqty.$sing.$qty_detail; //$rs["qty_order"];?></td>
						   <td style="white-space: nowrap; min-width: 120px;">&nbsp;<?php echo $rs["curr_name"]."&nbsp;";echo number_format($rs["price"],2);?></td>
						   <td style="white-space: nowrap; min-width: 120px;">&nbsp;<?php echo $rs["curr_name"]."&nbsp;".number_format($rs["sub_total"],2);?></td>
						</tr>
						   <?php 
                    }?>
                    <tr>
						<td colspan="3" rowspan="5" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000; font-size: 12px !important;">
							<table width="97%" style="margin: 5px;padding:5px; border:1px dotted #000; white-space: nowrap;">
								<tr>
									<td width="50%" align="left" style="text-align: left;padding:10px;">
									<style>
									.lblvalue{padding:2px; width: 185px; height: 28px; border: 1px solid #000; display: block;}
									</style>
										<table style="width: 100%">
											<tr>
												<td style="white-space: nowrap;"><span>បង់ប្រាក់ជា </span></td>
												<td><span class="lblvalue"><?php echo $this->product[0]['payment_method'];?></span></td>
											</tr>
											<tr>
												<td>លេខសែក</td>
												<td><span class="lblvalue"><?php echo $this->product[0]['payment_number'];?></span></td>
											</tr>
											<tr>
												<td>ថ្ងៃត្រូវចេញសែក</td>
												<td><span class="lblvalue"><?php echo empty($this->product[0]['date_issuecheque'])?"":date("d-m-Y",strtotime($this->product[0]['date_issuecheque']));?></span></td>
											</tr>
										</table>
									</td>
									<td width="50%" valign="top" style="padding:10px;">
										<table style="width: 100%; white-space: nowrap;" >
											<tr>
												<td style="white-space: nowrap;"><span>កម្រៃ​ </span></td>
												<td><span class="lblvalue"><?php echo $this->product[0]['commission'];?></span></td>
											</tr>
											<tr>
												<td>កម្រៃរ៉ាប់រង</td>
												<td><span class="lblvalue"><?php echo $this->product[0]['commission_ensur'];?></span></td>
											</tr>
											<tr>
												<td>ឈ្មោះធនាគារ</td>
												<td><span class="lblvalue"><?php echo $this->product[0]['bank_name'];?></span></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;Total</td>
						<td >&nbsp;&nbsp;<?php echo number_format($this->product[0]['net_total'],2);?></td>
					</tr>
					<tr>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;Discount</td>
						<td >&nbsp;&nbsp;<?php echo number_format($this->product[0]['discount_real'],2);?></td>
					</tr>
					<tr>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;Tax</td>
						<td >&nbsp;&nbsp;<?php echo number_format($this->product[0]['tax'],2);?></td>
					</tr>
					<tr>
						<td colspan="2" style="border-left:1px solid #000;">&nbsp;&nbsp;Deposit</td>
						<td >&nbsp;&nbsp;<?php echo number_format($this->product[0]['paid'],2);?></td>
					</tr>
					<tr>
						<td colspan="2" style="background:#ccc;border-left:1px solid #000;">&nbsp;&nbsp;Balance </td>
						<td style="background:#ccc;">&nbsp;&nbsp;<?php echo number_format($this->product[0]['balance'],2);//$this->product[0]['balance']-$this->product[0]['paid'];?></td>
					</tr>
		                </tbody>
		           </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
