<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$brach_name =  $this->branch;
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_PURCHASE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<?php $formFilter = $this->form_purchase; ?>
						<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status_paid');?></label>
					</div>
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('purchase_status');?></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_PURCHASE");?></li>
		                			<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("BRANCH_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("VENDOR_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("PURCHASE_ORDER");?></td>
							<td>&nbsp;<?php echo $tr->translate("INVOICE_NUMBER");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("ORDER_DATE");?></td>
							<td><?php echo $tr->translate("DATE_IN");?></td>
							<td>&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
							<td width="12%">&nbsp;<?php echo $tr->translate("PAID");?></td>
							<td>&nbsp;<?php echo $tr->translate("BALANCE");?></td>
							<td>&nbsp;<?php echo $tr->translate("PAYMENT_METHOD");?></td>
							<td>&nbsp;<?php echo $tr->translate("STATUS");?></td>
					        <td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
							<td style="white-space: nowrap;">&nbsp;<?php echo $tr->translate("PRINT");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000; <?php if($rs["balance_after"]<=0){echo"background:#d5daff;";}?>">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["vendor_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["order_number"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["invoice_no"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_order"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_in"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["paid"],2);?></td>
						   <td>&nbsp;<?php echo number_format($rs["balance_after"],2);?></td>
						   <td>&nbsp;<?php echo $rs["payment_method"];?></td>
						   <td>&nbsp;<?php echo $rs["purchase_status"];?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						   <td>&nbsp;<a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>"><?php echo $tr->translate("PRINT");?></a></td>
						</tr>
						   <?php 
							$d_netotal = $d_netotal+$rs["net_total"];
							$d_paid = $d_paid+$rs["paid"];
							$d_balance = $d_balance+$rs["balance_after"];
                    }?>
		                </tbody>
		           </table>
		            <br>
		             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                <tbody><tr height="30px;" bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
		                    <td><strong><?php echo $tr->translate("PURCHASE_AMOUNT");?></strong></td>
		                    <td><strong><?php echo $tr->translate("PAID");?></strong></td>
		                    <td><strong><?php echo $tr->translate("BALANCE");?></strong></td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:11px;">
		                    <td>&nbsp;<?php echo number_format($d_netotal,2);?>&nbsp;</td>
		                    <td>&nbsp;<?php echo number_format($d_paid,2);?>&nbsp;</td>
		                    <td>&nbsp;<?php echo number_format($d_balance,2);?>&nbsp;</td>
		                 </tr>
		               </tbody>
		             </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
