<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>Sale Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("SALES_REPORT");?>
				</div>
					<div class="btn-group pull-right">
						 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
						   Actions <i class="fa fa-angle-down"></i>
						 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>
						</ul>
				 </div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->form_purchase; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('customer_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('province_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('zone_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('saleagent_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('payment_balance');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 25px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
			}
			ul{margin: 0;padding:0;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			.hover:hover{background: #ccc;}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><!-- <img src="<?php //echo $this->baseUrl();?>/images/logo.jpg" height="55px"> --></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:14px; font-family:'Khmer OS Muol'"><?php //echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $tr->translate("SALES_REPORT");?></li>
		                			<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("INVOICE NUMBER");?></td>
							<td>&nbsp;<?php echo $tr->translate("SALE_AGENT");?></td>
							<td>&nbsp;<?php echo $tr->translate("PROVINCE_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("ZONE_NAME");?></td>
							<td><?php echo $tr->translate("SALE_DATE");?></td>
							<td><?php echo $tr->translate("PAYMENT_DATE");?></td>
							<td>&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
							<td>&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
							<td>&nbsp;<?php echo $tr->translate("GRAND_TOTAL");?></td>
							<td width="12%">&nbsp;<?php echo $tr->translate("PAID");?></td>
							<td>&nbsp;<?php echo $tr->translate("BALANCE");?></td>
							<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
		                </tr>
		                <?php $num=1; 
			                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
			                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
			                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
			                $all_total=0;
			                $discount=0;
		                if(!empty($this->repurchase))foreach ($this->repurchase AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["customer_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["sale_no"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/salesdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["agent_name"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["province"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["zone"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_sold"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["payment_date"]));?></td>
						   <td style="white-space: nowrap;"> <?php echo ($rs['net_total']==0)?"":"&nbsp;$&nbsp;".number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;"> <?php echo ($rs['discount_value']==0)?"":"&nbsp;$&nbsp;".number_format($rs["discount_value"],2);?></td>
						   <td style="white-space: nowrap;"> <?php echo ($rs['all_total']==0)?"":"&nbsp;$&nbsp;".number_format($rs["all_total"],2);?></td>
						   <td style="white-space: nowrap;"> <?php echo ($rs['paid']==0)?"":"&nbsp;$&nbsp;".number_format($rs["paid"],2);?></td>
						   <td><?php echo ($rs['balance']==0)?"":"&nbsp;$&nbsp;".number_format($rs["balance"],2);?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						</tr>
						   <?php 
								$d_netotal = $d_netotal+$rs["net_total"];
								$d_paid = $d_paid+$rs["paid"];
								$all_total = $all_total+$rs["all_total"];
								$d_balance = $d_balance+$rs["balance"];
								$discount=$discount +$rs["discount_value"];
                    }?>
		                </tbody>
		           </table>
		            <br>
		             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                <tbody><tr height="30px;" bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
		                    <td><strong><?php echo $tr->translate("AMOUNT");?></strong></td>
		                    <td>&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
		                    <td>&nbsp;<?php echo $tr->translate("GRAND_TOTAL");?></td>
		                    <td><strong><?php echo $tr->translate("PAID");?></strong></td>
		                    <td><strong><?php echo $tr->translate("BALANCE");?></strong></td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:12px;">
		                    <td> <?php echo ($d_netotal==0)?"":"&nbsp;$&nbsp;".number_format($d_netotal,2);?>&nbsp;</td>
		                    <td> <?php echo ($discount==0)?"":"&nbsp;$&nbsp;".number_format($discount,2);?>&nbsp;</td>
							<td> <?php echo ($all_total==0)?"":"&nbsp;$&nbsp;".number_format($all_total,2);?>&nbsp;</td>
		                    <td> <?php echo ($d_paid==0)?"":"&nbsp;$&nbsp;".number_format($d_paid,2);?>&nbsp;</td>
		                    <td> <?php echo ($d_balance==0)?"":"&nbsp;$&nbsp;".number_format($d_balance,2);?>&nbsp;</td>
		                 </tr>
		               </tbody>
		             </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  ">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; ">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
